/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AllocationItem model module.
 * @module model/AllocationItem
 */
class AllocationItem {
    /**
     * Constructs a new <code>AllocationItem</code>.
     * @alias module:model/AllocationItem
     * @param allocation_item_id {String} The allocation item ID generated by Cobo.
     * @param batch_allocation_id {String} The batch allocation ID generated by Cobo.
     * @param token_id {String} The ID of the cryptocurrency you want to allocation. Supported values:  - USDC: `ETH_USDC`, `ARBITRUM_USDC`, `SOL_USDC`, `BASE_USDC`, `MATIC_USDC`, `BSC_USDC` - USDT: `TRON_USDT`, `ETH_USDT`, `ARBITRUM_USDT`, `SOL_USDT`, `BASE_USDT`, `MATIC_USDT`, `BSC_USDT` 
     * @param amount {String} The allocation amount. 
     * @param description {String} The description of the allocation item.
     */
    constructor(allocation_item_id, batch_allocation_id, token_id, amount, description) { 
        
        AllocationItem.initialize(this, allocation_item_id, batch_allocation_id, token_id, amount, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, allocation_item_id, batch_allocation_id, token_id, amount, description) { 
        obj['allocation_item_id'] = allocation_item_id;
        obj['batch_allocation_id'] = batch_allocation_id;
        obj['token_id'] = token_id;
        obj['amount'] = amount;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>AllocationItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AllocationItem} obj Optional instance to populate.
     * @return {module:model/AllocationItem} The populated <code>AllocationItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllocationItem();

            if (data.hasOwnProperty('allocation_item_id')) {
                obj['allocation_item_id'] = ApiClient.convertToType(data['allocation_item_id'], 'String');
            }
            if (data.hasOwnProperty('batch_allocation_id')) {
                obj['batch_allocation_id'] = ApiClient.convertToType(data['batch_allocation_id'], 'String');
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('source_account')) {
                obj['source_account'] = ApiClient.convertToType(data['source_account'], 'String');
            }
            if (data.hasOwnProperty('destination_account')) {
                obj['destination_account'] = ApiClient.convertToType(data['destination_account'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AllocationItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AllocationItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AllocationItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['allocation_item_id'] && !(typeof data['allocation_item_id'] === 'string' || data['allocation_item_id'] instanceof String)) {
            throw new Error("Expected the field `allocation_item_id` to be a primitive type in the JSON string but got " + data['allocation_item_id']);
        }
        // ensure the json data is a string
        if (data['batch_allocation_id'] && !(typeof data['batch_allocation_id'] === 'string' || data['batch_allocation_id'] instanceof String)) {
            throw new Error("Expected the field `batch_allocation_id` to be a primitive type in the JSON string but got " + data['batch_allocation_id']);
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['source_account'] && !(typeof data['source_account'] === 'string' || data['source_account'] instanceof String)) {
            throw new Error("Expected the field `source_account` to be a primitive type in the JSON string but got " + data['source_account']);
        }
        // ensure the json data is a string
        if (data['destination_account'] && !(typeof data['destination_account'] === 'string' || data['destination_account'] instanceof String)) {
            throw new Error("Expected the field `destination_account` to be a primitive type in the JSON string but got " + data['destination_account']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

AllocationItem.RequiredProperties = ["allocation_item_id", "batch_allocation_id", "token_id", "amount", "description"];

/**
 * The allocation item ID generated by Cobo.
 * @member {String} allocation_item_id
 */
AllocationItem.prototype['allocation_item_id'] = undefined;

/**
 * The batch allocation ID generated by Cobo.
 * @member {String} batch_allocation_id
 */
AllocationItem.prototype['batch_allocation_id'] = undefined;

/**
 * The ID of the cryptocurrency you want to allocation. Supported values:  - USDC: `ETH_USDC`, `ARBITRUM_USDC`, `SOL_USDC`, `BASE_USDC`, `MATIC_USDC`, `BSC_USDC` - USDT: `TRON_USDT`, `ETH_USDT`, `ARBITRUM_USDT`, `SOL_USDT`, `BASE_USDT`, `MATIC_USDT`, `BSC_USDT` 
 * @member {String} token_id
 */
AllocationItem.prototype['token_id'] = undefined;

/**
 * The allocation amount. 
 * @member {String} amount
 */
AllocationItem.prototype['amount'] = undefined;

/**
 * The source account from which the allocation will be deducted. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. 
 * @member {String} source_account
 */
AllocationItem.prototype['source_account'] = undefined;

/**
 * The destination account to which the allocation will be credited. - If the destination account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the destination account is the developer account, use the string `\"developer\"`. 
 * @member {String} destination_account
 */
AllocationItem.prototype['destination_account'] = undefined;

/**
 * The description of the allocation item.
 * @member {String} description
 */
AllocationItem.prototype['description'] = undefined;






export default AllocationItem;

