/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AllocationRequest model module.
 * @module model/AllocationRequest
 */
class AllocationRequest {
    /**
     * Constructs a new <code>AllocationRequest</code>.
     * @alias module:model/AllocationRequest
     * @param token_id {String} The ID of the cryptocurrency you want to allocation. Supported values:  - USDC: `ETH_USDC`, `ARBITRUM_USDC`, `SOL_USDC`, `BASE_USDC`, `MATIC_USDC`, `BSC_USDC` - USDT: `TRON_USDT`, `ETH_USDT`, `ARBITRUM_USDT`, `SOL_USDT`, `BASE_USDT`, `MATIC_USDT`, `BSC_USDT` 
     * @param amount {String} The allocation amount. 
     * @param source_account {String} 
     * @param destination_account {String} 
     * @param description {String} 
     */
    constructor(token_id, amount, source_account, destination_account, description) { 
        
        AllocationRequest.initialize(this, token_id, amount, source_account, destination_account, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token_id, amount, source_account, destination_account, description) { 
        obj['token_id'] = token_id;
        obj['amount'] = amount;
        obj['source_account'] = source_account;
        obj['destination_account'] = destination_account;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>AllocationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AllocationRequest} obj Optional instance to populate.
     * @return {module:model/AllocationRequest} The populated <code>AllocationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AllocationRequest();

            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('source_account')) {
                obj['source_account'] = ApiClient.convertToType(data['source_account'], 'String');
            }
            if (data.hasOwnProperty('destination_account')) {
                obj['destination_account'] = ApiClient.convertToType(data['destination_account'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AllocationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AllocationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AllocationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['source_account'] && !(typeof data['source_account'] === 'string' || data['source_account'] instanceof String)) {
            throw new Error("Expected the field `source_account` to be a primitive type in the JSON string but got " + data['source_account']);
        }
        // ensure the json data is a string
        if (data['destination_account'] && !(typeof data['destination_account'] === 'string' || data['destination_account'] instanceof String)) {
            throw new Error("Expected the field `destination_account` to be a primitive type in the JSON string but got " + data['destination_account']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

AllocationRequest.RequiredProperties = ["token_id", "amount", "source_account", "destination_account", "description"];

/**
 * The ID of the cryptocurrency you want to allocation. Supported values:  - USDC: `ETH_USDC`, `ARBITRUM_USDC`, `SOL_USDC`, `BASE_USDC`, `MATIC_USDC`, `BSC_USDC` - USDT: `TRON_USDT`, `ETH_USDT`, `ARBITRUM_USDT`, `SOL_USDT`, `BASE_USDT`, `MATIC_USDT`, `BSC_USDT` 
 * @member {String} token_id
 */
AllocationRequest.prototype['token_id'] = undefined;

/**
 * The allocation amount. 
 * @member {String} amount
 */
AllocationRequest.prototype['amount'] = undefined;

/**
 * @member {String} source_account
 */
AllocationRequest.prototype['source_account'] = undefined;

/**
 * @member {String} destination_account
 */
AllocationRequest.prototype['destination_account'] = undefined;

/**
 * @member {String} description
 */
AllocationRequest.prototype['description'] = undefined;






export default AllocationRequest;

