/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BridgingFee model module.
 * @module model/BridgingFee
 */
class BridgingFee {
    /**
     * Constructs a new <code>BridgingFee</code>.
     * @alias module:model/BridgingFee
     * @param fee_amount {String} The bridging fee amount.
     */
    constructor(fee_amount) { 
        
        BridgingFee.initialize(this, fee_amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, fee_amount) { 
        obj['fee_amount'] = fee_amount;
    }

    /**
     * Constructs a <code>BridgingFee</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BridgingFee} obj Optional instance to populate.
     * @return {module:model/BridgingFee} The populated <code>BridgingFee</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BridgingFee();

            if (data.hasOwnProperty('fee_amount')) {
                obj['fee_amount'] = ApiClient.convertToType(data['fee_amount'], 'String');
            }
            if (data.hasOwnProperty('received_token_id')) {
                obj['received_token_id'] = ApiClient.convertToType(data['received_token_id'], 'String');
            }
            if (data.hasOwnProperty('received_amount')) {
                obj['received_amount'] = ApiClient.convertToType(data['received_amount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BridgingFee</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BridgingFee</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BridgingFee.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['fee_amount'] && !(typeof data['fee_amount'] === 'string' || data['fee_amount'] instanceof String)) {
            throw new Error("Expected the field `fee_amount` to be a primitive type in the JSON string but got " + data['fee_amount']);
        }
        // ensure the json data is a string
        if (data['received_token_id'] && !(typeof data['received_token_id'] === 'string' || data['received_token_id'] instanceof String)) {
            throw new Error("Expected the field `received_token_id` to be a primitive type in the JSON string but got " + data['received_token_id']);
        }
        // ensure the json data is a string
        if (data['received_amount'] && !(typeof data['received_amount'] === 'string' || data['received_amount'] instanceof String)) {
            throw new Error("Expected the field `received_amount` to be a primitive type in the JSON string but got " + data['received_amount']);
        }

        return true;
    }


}

BridgingFee.RequiredProperties = ["fee_amount"];

/**
 * The bridging fee amount.
 * @member {String} fee_amount
 */
BridgingFee.prototype['fee_amount'] = undefined;

/**
 * The received token id after bridge.
 * @member {String} received_token_id
 */
BridgingFee.prototype['received_token_id'] = undefined;

/**
 * The received amount after bridge.
 * @member {String} received_amount
 */
BridgingFee.prototype['received_amount'] = undefined;






export default BridgingFee;

