/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CommissionFeeDetailNormalizedAmount from './CommissionFeeDetailNormalizedAmount';
import SettleType from './SettleType';
import StrategyParams from './StrategyParams';

/**
 * The CommissionFeeDetail model module.
 * @module model/CommissionFeeDetail
 */
class CommissionFeeDetail {
    /**
     * Constructs a new <code>CommissionFeeDetail</code>.
     * Commission fee detail
     * @alias module:model/CommissionFeeDetail
     */
    constructor() { 
        
        CommissionFeeDetail.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CommissionFeeDetail</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CommissionFeeDetail} obj Optional instance to populate.
     * @return {module:model/CommissionFeeDetail} The populated <code>CommissionFeeDetail</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CommissionFeeDetail();

            if (data.hasOwnProperty('commission_fee_id')) {
                obj['commission_fee_id'] = ApiClient.convertToType(data['commission_fee_id'], 'String');
            }
            if (data.hasOwnProperty('asset_id')) {
                obj['asset_id'] = ApiClient.convertToType(data['asset_id'], 'String');
            }
            if (data.hasOwnProperty('fee_tokens')) {
                obj['fee_tokens'] = ApiClient.convertToType(data['fee_tokens'], ['String']);
            }
            if (data.hasOwnProperty('settle_type')) {
                obj['settle_type'] = SettleType.constructFromObject(data['settle_type']);
            }
            if (data.hasOwnProperty('business_type_id')) {
                obj['business_type_id'] = ApiClient.convertToType(data['business_type_id'], 'Number');
            }
            if (data.hasOwnProperty('normalized_amount')) {
                obj['normalized_amount'] = CommissionFeeDetailNormalizedAmount.constructFromObject(data['normalized_amount']);
            }
            if (data.hasOwnProperty('strategy_id')) {
                obj['strategy_id'] = ApiClient.convertToType(data['strategy_id'], 'Number');
            }
            if (data.hasOwnProperty('rule_id')) {
                obj['rule_id'] = ApiClient.convertToType(data['rule_id'], 'Number');
            }
            if (data.hasOwnProperty('strategy_params')) {
                obj['strategy_params'] = StrategyParams.constructFromObject(data['strategy_params']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CommissionFeeDetail</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CommissionFeeDetail</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['commission_fee_id'] && !(typeof data['commission_fee_id'] === 'string' || data['commission_fee_id'] instanceof String)) {
            throw new Error("Expected the field `commission_fee_id` to be a primitive type in the JSON string but got " + data['commission_fee_id']);
        }
        // ensure the json data is a string
        if (data['asset_id'] && !(typeof data['asset_id'] === 'string' || data['asset_id'] instanceof String)) {
            throw new Error("Expected the field `asset_id` to be a primitive type in the JSON string but got " + data['asset_id']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['fee_tokens'])) {
            throw new Error("Expected the field `fee_tokens` to be an array in the JSON data but got " + data['fee_tokens']);
        }
        // validate the optional field `normalized_amount`
        if (data['normalized_amount']) { // data not null
          if (!!CommissionFeeDetailNormalizedAmount.validateJSON) {
            CommissionFeeDetailNormalizedAmount.validateJSON(data['normalized_amount']);
          }
        }
        // validate the optional field `strategy_params`
        if (data['strategy_params']) { // data not null
          if (!!StrategyParams.validateJSON) {
            StrategyParams.validateJSON(data['strategy_params']);
          }
        }

        return true;
    }


}



/**
 * Unique ID of the commission fee
 * @member {String} commission_fee_id
 */
CommissionFeeDetail.prototype['commission_fee_id'] = undefined;

/**
 * Asset ID
 * @member {String} asset_id
 */
CommissionFeeDetail.prototype['asset_id'] = undefined;

/**
 * List of fee token IDs
 * @member {Array.<String>} fee_tokens
 */
CommissionFeeDetail.prototype['fee_tokens'] = undefined;

/**
 * @member {module:model/SettleType} settle_type
 */
CommissionFeeDetail.prototype['settle_type'] = undefined;

/**
 * Unique ID of business type
 * @member {Number} business_type_id
 */
CommissionFeeDetail.prototype['business_type_id'] = undefined;

/**
 * @member {module:model/CommissionFeeDetailNormalizedAmount} normalized_amount
 */
CommissionFeeDetail.prototype['normalized_amount'] = undefined;

/**
 * Strategy ID
 * @member {Number} strategy_id
 */
CommissionFeeDetail.prototype['strategy_id'] = undefined;

/**
 * Rule ID
 * @member {Number} rule_id
 */
CommissionFeeDetail.prototype['rule_id'] = undefined;

/**
 * @member {module:model/StrategyParams} strategy_params
 */
CommissionFeeDetail.prototype['strategy_params'] = undefined;






export default CommissionFeeDetail;

