/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DestinationBankAccount from './DestinationBankAccount';
import WalletAddress from './WalletAddress';

/**
 * The CreateDestinationEntry201Response model module.
 * @module model/CreateDestinationEntry201Response
 */
class CreateDestinationEntry201Response {
    /**
     * Constructs a new <code>CreateDestinationEntry201Response</code>.
     * @alias module:model/CreateDestinationEntry201Response
     * @param destination_id {String} The destination ID.
     */
    constructor(destination_id) { 
        
        CreateDestinationEntry201Response.initialize(this, destination_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, destination_id) { 
        obj['destination_id'] = destination_id;
    }

    /**
     * Constructs a <code>CreateDestinationEntry201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateDestinationEntry201Response} obj Optional instance to populate.
     * @return {module:model/CreateDestinationEntry201Response} The populated <code>CreateDestinationEntry201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateDestinationEntry201Response();

            if (data.hasOwnProperty('destination_id')) {
                obj['destination_id'] = ApiClient.convertToType(data['destination_id'], 'String');
            }
            if (data.hasOwnProperty('wallet_addresses')) {
                obj['wallet_addresses'] = ApiClient.convertToType(data['wallet_addresses'], [WalletAddress]);
            }
            if (data.hasOwnProperty('bank_accounts')) {
                obj['bank_accounts'] = ApiClient.convertToType(data['bank_accounts'], [DestinationBankAccount]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateDestinationEntry201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateDestinationEntry201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateDestinationEntry201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['destination_id'] && !(typeof data['destination_id'] === 'string' || data['destination_id'] instanceof String)) {
            throw new Error("Expected the field `destination_id` to be a primitive type in the JSON string but got " + data['destination_id']);
        }
        if (data['wallet_addresses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['wallet_addresses'])) {
                throw new Error("Expected the field `wallet_addresses` to be an array in the JSON data but got " + data['wallet_addresses']);
            }
            // validate the optional field `wallet_addresses` (array)
            for (const item of data['wallet_addresses']) {
                WalletAddress.validateJSON(item);
            };
        }
        if (data['bank_accounts']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['bank_accounts'])) {
                throw new Error("Expected the field `bank_accounts` to be an array in the JSON data but got " + data['bank_accounts']);
            }
            // validate the optional field `bank_accounts` (array)
            for (const item of data['bank_accounts']) {
                DestinationBankAccount.validateJSON(item);
            };
        }

        return true;
    }


}

CreateDestinationEntry201Response.RequiredProperties = ["destination_id"];

/**
 * The destination ID.
 * @member {String} destination_id
 */
CreateDestinationEntry201Response.prototype['destination_id'] = undefined;

/**
 * The wallet addresses of the destination.
 * @member {Array.<module:model/WalletAddress>} wallet_addresses
 */
CreateDestinationEntry201Response.prototype['wallet_addresses'] = undefined;

/**
 * The bank accounts of the destination.
 * @member {Array.<module:model/DestinationBankAccount>} bank_accounts
 */
CreateDestinationEntry201Response.prototype['bank_accounts'] = undefined;






export default CreateDestinationEntry201Response;

