/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCounterpartyWalletAddressRequest model module.
 * @module model/CreateCounterpartyWalletAddressRequest
 */
class CreateCounterpartyWalletAddressRequest {
    /**
     * Constructs a new <code>CreateCounterpartyWalletAddressRequest</code>.
     * @alias module:model/CreateCounterpartyWalletAddressRequest
     * @param counterparty_id {String} The counterparty ID.
     * @param address {String} The wallet address.
     * @param chain_id {String} The chain ID of the cryptocurrency.
     */
    constructor(counterparty_id, address, chain_id) { 
        
        CreateCounterpartyWalletAddressRequest.initialize(this, counterparty_id, address, chain_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, counterparty_id, address, chain_id) { 
        obj['counterparty_id'] = counterparty_id;
        obj['address'] = address;
        obj['chain_id'] = chain_id;
    }

    /**
     * Constructs a <code>CreateCounterpartyWalletAddressRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCounterpartyWalletAddressRequest} obj Optional instance to populate.
     * @return {module:model/CreateCounterpartyWalletAddressRequest} The populated <code>CreateCounterpartyWalletAddressRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCounterpartyWalletAddressRequest();

            if (data.hasOwnProperty('counterparty_id')) {
                obj['counterparty_id'] = ApiClient.convertToType(data['counterparty_id'], 'String');
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('chain_id')) {
                obj['chain_id'] = ApiClient.convertToType(data['chain_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateCounterpartyWalletAddressRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateCounterpartyWalletAddressRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateCounterpartyWalletAddressRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['counterparty_id'] && !(typeof data['counterparty_id'] === 'string' || data['counterparty_id'] instanceof String)) {
            throw new Error("Expected the field `counterparty_id` to be a primitive type in the JSON string but got " + data['counterparty_id']);
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['chain_id'] && !(typeof data['chain_id'] === 'string' || data['chain_id'] instanceof String)) {
            throw new Error("Expected the field `chain_id` to be a primitive type in the JSON string but got " + data['chain_id']);
        }

        return true;
    }


}

CreateCounterpartyWalletAddressRequest.RequiredProperties = ["counterparty_id", "address", "chain_id"];

/**
 * The counterparty ID.
 * @member {String} counterparty_id
 */
CreateCounterpartyWalletAddressRequest.prototype['counterparty_id'] = undefined;

/**
 * The wallet address.
 * @member {String} address
 */
CreateCounterpartyWalletAddressRequest.prototype['address'] = undefined;

/**
 * The chain ID of the cryptocurrency.
 * @member {String} chain_id
 */
CreateCounterpartyWalletAddressRequest.prototype['chain_id'] = undefined;






export default CreateCounterpartyWalletAddressRequest;

