/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutMode from './PayoutMode';
import PayoutStatus from './PayoutStatus';

/**
 * The CreateBatchPayout201Response model module.
 * @module model/CreateBatchPayout201Response
 */
class CreateBatchPayout201Response {
    /**
     * Constructs a new <code>CreateBatchPayout201Response</code>.
     * @alias module:model/CreateBatchPayout201Response
     * @param payout_id {String} The payout ID.
     * @param payout_mode {module:model/PayoutMode} 
     * @param status {module:model/PayoutStatus} 
     * @param estimated_total_fee {String} The total fee of the payout.
     * @param created_timestamp {Number} The created time of the payout, represented as a UNIX timestamp in seconds.
     */
    constructor(payout_id, payout_mode, status, estimated_total_fee, created_timestamp) { 
        
        CreateBatchPayout201Response.initialize(this, payout_id, payout_mode, status, estimated_total_fee, created_timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, payout_id, payout_mode, status, estimated_total_fee, created_timestamp) { 
        obj['payout_id'] = payout_id;
        obj['payout_mode'] = payout_mode;
        obj['status'] = status;
        obj['estimated_total_fee'] = estimated_total_fee;
        obj['created_timestamp'] = created_timestamp;
    }

    /**
     * Constructs a <code>CreateBatchPayout201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateBatchPayout201Response} obj Optional instance to populate.
     * @return {module:model/CreateBatchPayout201Response} The populated <code>CreateBatchPayout201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateBatchPayout201Response();

            if (data.hasOwnProperty('payout_id')) {
                obj['payout_id'] = ApiClient.convertToType(data['payout_id'], 'String');
            }
            if (data.hasOwnProperty('payout_mode')) {
                obj['payout_mode'] = PayoutMode.constructFromObject(data['payout_mode']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PayoutStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('estimated_total_fee')) {
                obj['estimated_total_fee'] = ApiClient.convertToType(data['estimated_total_fee'], 'String');
            }
            if (data.hasOwnProperty('created_timestamp')) {
                obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateBatchPayout201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateBatchPayout201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateBatchPayout201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['payout_id'] && !(typeof data['payout_id'] === 'string' || data['payout_id'] instanceof String)) {
            throw new Error("Expected the field `payout_id` to be a primitive type in the JSON string but got " + data['payout_id']);
        }
        // ensure the json data is a string
        if (data['estimated_total_fee'] && !(typeof data['estimated_total_fee'] === 'string' || data['estimated_total_fee'] instanceof String)) {
            throw new Error("Expected the field `estimated_total_fee` to be a primitive type in the JSON string but got " + data['estimated_total_fee']);
        }

        return true;
    }


}

CreateBatchPayout201Response.RequiredProperties = ["payout_id", "payout_mode", "status", "estimated_total_fee", "created_timestamp"];

/**
 * The payout ID.
 * @member {String} payout_id
 */
CreateBatchPayout201Response.prototype['payout_id'] = undefined;

/**
 * @member {module:model/PayoutMode} payout_mode
 */
CreateBatchPayout201Response.prototype['payout_mode'] = undefined;

/**
 * @member {module:model/PayoutStatus} status
 */
CreateBatchPayout201Response.prototype['status'] = undefined;

/**
 * The total fee of the payout.
 * @member {String} estimated_total_fee
 */
CreateBatchPayout201Response.prototype['estimated_total_fee'] = undefined;

/**
 * The created time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
CreateBatchPayout201Response.prototype['created_timestamp'] = undefined;






export default CreateBatchPayout201Response;

