/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentPayoutParam from './PaymentPayoutParam';
import PaymentPayoutRecipientInfo from './PaymentPayoutRecipientInfo';
import PayoutChannel from './PayoutChannel';

/**
 * The CreatePayoutRequest model module.
 * @module model/CreatePayoutRequest
 */
class CreatePayoutRequest {
    /**
     * Constructs a new <code>CreatePayoutRequest</code>.
     * @alias module:model/CreatePayoutRequest
     * @param request_id {String} The request ID that is used to track a payout request. The request ID is provided by you and must be unique.
     * @param source_account {String} The source account from which the payout will be made. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. 
     * @param payout_channel {module:model/PayoutChannel} 
     * @param payout_params {Array.<module:model/PaymentPayoutParam>} 
     * @param recipient_info {module:model/PaymentPayoutRecipientInfo} 
     */
    constructor(request_id, source_account, payout_channel, payout_params, recipient_info) { 
        
        CreatePayoutRequest.initialize(this, request_id, source_account, payout_channel, payout_params, recipient_info);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, request_id, source_account, payout_channel, payout_params, recipient_info) { 
        obj['request_id'] = request_id;
        obj['source_account'] = source_account;
        obj['payout_channel'] = payout_channel;
        obj['payout_params'] = payout_params;
        obj['recipient_info'] = recipient_info;
    }

    /**
     * Constructs a <code>CreatePayoutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreatePayoutRequest} obj Optional instance to populate.
     * @return {module:model/CreatePayoutRequest} The populated <code>CreatePayoutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreatePayoutRequest();

            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
            if (data.hasOwnProperty('source_account')) {
                obj['source_account'] = ApiClient.convertToType(data['source_account'], 'String');
            }
            if (data.hasOwnProperty('payout_channel')) {
                obj['payout_channel'] = PayoutChannel.constructFromObject(data['payout_channel']);
            }
            if (data.hasOwnProperty('payout_params')) {
                obj['payout_params'] = ApiClient.convertToType(data['payout_params'], [PaymentPayoutParam]);
            }
            if (data.hasOwnProperty('recipient_info')) {
                obj['recipient_info'] = PaymentPayoutRecipientInfo.constructFromObject(data['recipient_info']);
            }
            if (data.hasOwnProperty('remark')) {
                obj['remark'] = ApiClient.convertToType(data['remark'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreatePayoutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreatePayoutRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreatePayoutRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['request_id'] && !(typeof data['request_id'] === 'string' || data['request_id'] instanceof String)) {
            throw new Error("Expected the field `request_id` to be a primitive type in the JSON string but got " + data['request_id']);
        }
        // ensure the json data is a string
        if (data['source_account'] && !(typeof data['source_account'] === 'string' || data['source_account'] instanceof String)) {
            throw new Error("Expected the field `source_account` to be a primitive type in the JSON string but got " + data['source_account']);
        }
        if (data['payout_params']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['payout_params'])) {
                throw new Error("Expected the field `payout_params` to be an array in the JSON data but got " + data['payout_params']);
            }
            // validate the optional field `payout_params` (array)
            for (const item of data['payout_params']) {
                PaymentPayoutParam.validateJSON(item);
            };
        }
        // validate the optional field `recipient_info`
        if (data['recipient_info']) { // data not null
          if (!!PaymentPayoutRecipientInfo.validateJSON) {
            PaymentPayoutRecipientInfo.validateJSON(data['recipient_info']);
          }
        }
        // ensure the json data is a string
        if (data['remark'] && !(typeof data['remark'] === 'string' || data['remark'] instanceof String)) {
            throw new Error("Expected the field `remark` to be a primitive type in the JSON string but got " + data['remark']);
        }

        return true;
    }


}

CreatePayoutRequest.RequiredProperties = ["request_id", "source_account", "payout_channel", "payout_params", "recipient_info"];

/**
 * The request ID that is used to track a payout request. The request ID is provided by you and must be unique.
 * @member {String} request_id
 */
CreatePayoutRequest.prototype['request_id'] = undefined;

/**
 * The source account from which the payout will be made. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. 
 * @member {String} source_account
 */
CreatePayoutRequest.prototype['source_account'] = undefined;

/**
 * @member {module:model/PayoutChannel} payout_channel
 */
CreatePayoutRequest.prototype['payout_channel'] = undefined;

/**
 * @member {Array.<module:model/PaymentPayoutParam>} payout_params
 */
CreatePayoutRequest.prototype['payout_params'] = undefined;

/**
 * @member {module:model/PaymentPayoutRecipientInfo} recipient_info
 */
CreatePayoutRequest.prototype['recipient_info'] = undefined;

/**
 * An optional note or comment about the payout for your internal reference.
 * @member {String} remark
 */
CreatePayoutRequest.prototype['remark'] = undefined;






export default CreatePayoutRequest;

