/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateWalletAddress from './CreateWalletAddress';

/**
 * The CreateCounterpartyEntryRequest model module.
 * @module model/CreateCounterpartyEntryRequest
 */
class CreateCounterpartyEntryRequest {
    /**
     * Constructs a new <code>CreateCounterpartyEntryRequest</code>.
     * @alias module:model/CreateCounterpartyEntryRequest
     * @param counterparty_id {String} The counterparty ID.
     */
    constructor(counterparty_id) { 
        
        CreateCounterpartyEntryRequest.initialize(this, counterparty_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, counterparty_id) { 
        obj['counterparty_id'] = counterparty_id;
    }

    /**
     * Constructs a <code>CreateCounterpartyEntryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCounterpartyEntryRequest} obj Optional instance to populate.
     * @return {module:model/CreateCounterpartyEntryRequest} The populated <code>CreateCounterpartyEntryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCounterpartyEntryRequest();

            if (data.hasOwnProperty('counterparty_id')) {
                obj['counterparty_id'] = ApiClient.convertToType(data['counterparty_id'], 'String');
            }
            if (data.hasOwnProperty('wallet_addresses')) {
                obj['wallet_addresses'] = ApiClient.convertToType(data['wallet_addresses'], [CreateWalletAddress]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateCounterpartyEntryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateCounterpartyEntryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateCounterpartyEntryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['counterparty_id'] && !(typeof data['counterparty_id'] === 'string' || data['counterparty_id'] instanceof String)) {
            throw new Error("Expected the field `counterparty_id` to be a primitive type in the JSON string but got " + data['counterparty_id']);
        }
        if (data['wallet_addresses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['wallet_addresses'])) {
                throw new Error("Expected the field `wallet_addresses` to be an array in the JSON data but got " + data['wallet_addresses']);
            }
            // validate the optional field `wallet_addresses` (array)
            for (const item of data['wallet_addresses']) {
                CreateWalletAddress.validateJSON(item);
            };
        }

        return true;
    }


}

CreateCounterpartyEntryRequest.RequiredProperties = ["counterparty_id"];

/**
 * The counterparty ID.
 * @member {String} counterparty_id
 */
CreateCounterpartyEntryRequest.prototype['counterparty_id'] = undefined;

/**
 * The wallet addresses of the counterparty.
 * @member {Array.<module:model/CreateWalletAddress>} wallet_addresses
 */
CreateCounterpartyEntryRequest.prototype['wallet_addresses'] = undefined;






export default CreateCounterpartyEntryRequest;

