/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateWalletAddress model module.
 * @module model/CreateWalletAddress
 */
class CreateWalletAddress {
    /**
     * Constructs a new <code>CreateWalletAddress</code>.
     * @alias module:model/CreateWalletAddress
     * @param address {String} The wallet address.
     * @param chain_id {String} The chain ID of the cryptocurrency.
     */
    constructor(address, chain_id) { 
        
        CreateWalletAddress.initialize(this, address, chain_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, chain_id) { 
        obj['address'] = address;
        obj['chain_id'] = chain_id;
    }

    /**
     * Constructs a <code>CreateWalletAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateWalletAddress} obj Optional instance to populate.
     * @return {module:model/CreateWalletAddress} The populated <code>CreateWalletAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateWalletAddress();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('chain_id')) {
                obj['chain_id'] = ApiClient.convertToType(data['chain_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateWalletAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateWalletAddress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateWalletAddress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['chain_id'] && !(typeof data['chain_id'] === 'string' || data['chain_id'] instanceof String)) {
            throw new Error("Expected the field `chain_id` to be a primitive type in the JSON string but got " + data['chain_id']);
        }

        return true;
    }


}

CreateWalletAddress.RequiredProperties = ["address", "chain_id"];

/**
 * The wallet address.
 * @member {String} address
 */
CreateWalletAddress.prototype['address'] = undefined;

/**
 * The chain ID of the cryptocurrency.
 * @member {String} chain_id
 */
CreateWalletAddress.prototype['chain_id'] = undefined;






export default CreateWalletAddress;

