/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import WebhookEventType from './WebhookEventType';

/**
 * The CreateWebhookEventParams model module.
 * @module model/CreateWebhookEventParams
 */
class CreateWebhookEventParams {
    /**
     * Constructs a new <code>CreateWebhookEventParams</code>.
     * The webhook event payload.
     * @alias module:model/CreateWebhookEventParams
     * @param channel_id {String} Identifier for the client/organization. Corresponds to organization_id in Cobo Portal.
     * @param type {module:model/WebhookEventType} 
     * @param data {Object.<String, Object>} The event payload object.
     * @param uuid {String} Unique event identifier.
     */
    constructor(channel_id, type, data, uuid) { 
        
        CreateWebhookEventParams.initialize(this, channel_id, type, data, uuid);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, channel_id, type, data, uuid) { 
        obj['channel_id'] = channel_id;
        obj['type'] = type;
        obj['data'] = data;
        obj['uuid'] = uuid;
    }

    /**
     * Constructs a <code>CreateWebhookEventParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateWebhookEventParams} obj Optional instance to populate.
     * @return {module:model/CreateWebhookEventParams} The populated <code>CreateWebhookEventParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateWebhookEventParams();

            if (data.hasOwnProperty('channel_id')) {
                obj['channel_id'] = ApiClient.convertToType(data['channel_id'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = WebhookEventType.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], {'String': Object});
            }
            if (data.hasOwnProperty('uuid')) {
                obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
            }
            if (data.hasOwnProperty('wallet_scopes_info')) {
                obj['wallet_scopes_info'] = ApiClient.convertToType(data['wallet_scopes_info'], {'String': Object});
            }
            if (data.hasOwnProperty('transaction_hash')) {
                obj['transaction_hash'] = ApiClient.convertToType(data['transaction_hash'], 'String');
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
            if (data.hasOwnProperty('transaction_id')) {
                obj['transaction_id'] = ApiClient.convertToType(data['transaction_id'], 'String');
            }
            if (data.hasOwnProperty('cobo_id')) {
                obj['cobo_id'] = ApiClient.convertToType(data['cobo_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateWebhookEventParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateWebhookEventParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateWebhookEventParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['channel_id'] && !(typeof data['channel_id'] === 'string' || data['channel_id'] instanceof String)) {
            throw new Error("Expected the field `channel_id` to be a primitive type in the JSON string but got " + data['channel_id']);
        }
        // ensure the json data is a string
        if (data['uuid'] && !(typeof data['uuid'] === 'string' || data['uuid'] instanceof String)) {
            throw new Error("Expected the field `uuid` to be a primitive type in the JSON string but got " + data['uuid']);
        }
        // ensure the json data is a string
        if (data['transaction_hash'] && !(typeof data['transaction_hash'] === 'string' || data['transaction_hash'] instanceof String)) {
            throw new Error("Expected the field `transaction_hash` to be a primitive type in the JSON string but got " + data['transaction_hash']);
        }
        // ensure the json data is a string
        if (data['request_id'] && !(typeof data['request_id'] === 'string' || data['request_id'] instanceof String)) {
            throw new Error("Expected the field `request_id` to be a primitive type in the JSON string but got " + data['request_id']);
        }
        // ensure the json data is a string
        if (data['transaction_id'] && !(typeof data['transaction_id'] === 'string' || data['transaction_id'] instanceof String)) {
            throw new Error("Expected the field `transaction_id` to be a primitive type in the JSON string but got " + data['transaction_id']);
        }
        // ensure the json data is a string
        if (data['cobo_id'] && !(typeof data['cobo_id'] === 'string' || data['cobo_id'] instanceof String)) {
            throw new Error("Expected the field `cobo_id` to be a primitive type in the JSON string but got " + data['cobo_id']);
        }

        return true;
    }


}

CreateWebhookEventParams.RequiredProperties = ["channel_id", "type", "data", "uuid"];

/**
 * Identifier for the client/organization. Corresponds to organization_id in Cobo Portal.
 * @member {String} channel_id
 */
CreateWebhookEventParams.prototype['channel_id'] = undefined;

/**
 * @member {module:model/WebhookEventType} type
 */
CreateWebhookEventParams.prototype['type'] = undefined;

/**
 * The event payload object.
 * @member {Object.<String, Object>} data
 */
CreateWebhookEventParams.prototype['data'] = undefined;

/**
 * Unique event identifier.
 * @member {String} uuid
 */
CreateWebhookEventParams.prototype['uuid'] = undefined;

/**
 * Wallet scope information.
 * @member {Object.<String, Object>} wallet_scopes_info
 */
CreateWebhookEventParams.prototype['wallet_scopes_info'] = undefined;

/**
 * Blockchain transaction hash.
 * @member {String} transaction_hash
 */
CreateWebhookEventParams.prototype['transaction_hash'] = undefined;

/**
 * Request identifier.
 * @member {String} request_id
 */
CreateWebhookEventParams.prototype['request_id'] = undefined;

/**
 * Internal transaction identifier.
 * @member {String} transaction_id
 */
CreateWebhookEventParams.prototype['transaction_id'] = undefined;

/**
 * Cobo internal identifier.
 * @member {String} cobo_id
 */
CreateWebhookEventParams.prototype['cobo_id'] = undefined;






export default CreateWebhookEventParams;

