/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteAddressBookById201Response model module.
 * @module model/DeleteAddressBookById201Response
 */
class DeleteAddressBookById201Response {
    /**
     * Constructs a new <code>DeleteAddressBookById201Response</code>.
     * @alias module:model/DeleteAddressBookById201Response
     * @param submitted {Boolean} Whether the request to delete the Address Book entry (record) has been successfully submitted. - `true`: The request has been successfully submitted. - `false`: The request has not been submitted. 
     */
    constructor(submitted) { 
        
        DeleteAddressBookById201Response.initialize(this, submitted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, submitted) { 
        obj['submitted'] = submitted;
    }

    /**
     * Constructs a <code>DeleteAddressBookById201Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteAddressBookById201Response} obj Optional instance to populate.
     * @return {module:model/DeleteAddressBookById201Response} The populated <code>DeleteAddressBookById201Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteAddressBookById201Response();

            if (data.hasOwnProperty('submitted')) {
                obj['submitted'] = ApiClient.convertToType(data['submitted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteAddressBookById201Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteAddressBookById201Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteAddressBookById201Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

DeleteAddressBookById201Response.RequiredProperties = ["submitted"];

/**
 * Whether the request to delete the Address Book entry (record) has been successfully submitted. - `true`: The request has been successfully submitted. - `false`: The request has not been submitted. 
 * @member {Boolean} submitted
 */
DeleteAddressBookById201Response.prototype['submitted'] = undefined;






export default DeleteAddressBookById201Response;

