/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DeleteCounterparty200Response model module.
 * @module model/DeleteCounterparty200Response
 */
class DeleteCounterparty200Response {
    /**
     * Constructs a new <code>DeleteCounterparty200Response</code>.
     * @alias module:model/DeleteCounterparty200Response
     * @param counterparty_id {String} The counterparty ID.
     */
    constructor(counterparty_id) { 
        
        DeleteCounterparty200Response.initialize(this, counterparty_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, counterparty_id) { 
        obj['counterparty_id'] = counterparty_id;
    }

    /**
     * Constructs a <code>DeleteCounterparty200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DeleteCounterparty200Response} obj Optional instance to populate.
     * @return {module:model/DeleteCounterparty200Response} The populated <code>DeleteCounterparty200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DeleteCounterparty200Response();

            if (data.hasOwnProperty('counterparty_id')) {
                obj['counterparty_id'] = ApiClient.convertToType(data['counterparty_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DeleteCounterparty200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DeleteCounterparty200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DeleteCounterparty200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['counterparty_id'] && !(typeof data['counterparty_id'] === 'string' || data['counterparty_id'] instanceof String)) {
            throw new Error("Expected the field `counterparty_id` to be a primitive type in the JSON string but got " + data['counterparty_id']);
        }

        return true;
    }


}

DeleteCounterparty200Response.RequiredProperties = ["counterparty_id"];

/**
 * The counterparty ID.
 * @member {String} counterparty_id
 */
DeleteCounterparty200Response.prototype['counterparty_id'] = undefined;






export default DeleteCounterparty200Response;

