/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class DispositionStatus.
* @enum {}
* @readonly
*/
export default class DispositionStatus {
    
        /**
         * value: "Submitted"
         * @const
         */
        "Submitted" = "Submitted";

    
        /**
         * value: "Refunding"
         * @const
         */
        "Refunding" = "Refunding";

    
        /**
         * value: "Refunded"
         * @const
         */
        "Refunded" = "Refunded";

    
        /**
         * value: "RefundFailed"
         * @const
         */
        "RefundFailed" = "RefundFailed";

    
        /**
         * value: "Frozen"
         * @const
         */
        "Frozen" = "Frozen";

    
        /**
         * value: "Unfreezing"
         * @const
         */
        "Unfreezing" = "Unfreezing";

    
        /**
         * value: "Unfrozen"
         * @const
         */
        "Unfrozen" = "Unfrozen";

    
        /**
         * value: "UnfreezeFailed"
         * @const
         */
        "UnfreezeFailed" = "UnfreezeFailed";

    
        /**
         * value: "Isolating"
         * @const
         */
        "Isolating" = "Isolating";

    
        /**
         * value: "Isolated"
         * @const
         */
        "Isolated" = "Isolated";

    
        /**
         * value: "IsolateFailed"
         * @const
         */
        "IsolateFailed" = "IsolateFailed";

    
        /**
         * value: "CoboDisposition"
         * @const
         */
        "CoboDisposition" = "CoboDisposition";

    
        /**
         * value: "Normal"
         * @const
         */
        "Normal" = "Normal";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>DispositionStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/DispositionStatus} The enum <code>DispositionStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

