/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PayoutDestination from './PayoutDestination';
import PayoutMode from './PayoutMode';
import PayoutRbfType from './PayoutRbfType';
import PayoutSource from './PayoutSource';

/**
 * The EstimateBatchPayoutFeeRequest model module.
 * @module model/EstimateBatchPayoutFeeRequest
 */
class EstimateBatchPayoutFeeRequest {
    /**
     * Constructs a new <code>EstimateBatchPayoutFeeRequest</code>.
     * @alias module:model/EstimateBatchPayoutFeeRequest
     * @param token_id {String} The ID of the cryptocurrency used for payout. 
     * @param payout_mode {module:model/PayoutMode} 
     * @param source {module:model/PayoutSource} 
     * @param destinations {Array.<module:model/PayoutDestination>} The destinations of the payout.
     */
    constructor(token_id, payout_mode, source, destinations) { 
        
        EstimateBatchPayoutFeeRequest.initialize(this, token_id, payout_mode, source, destinations);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token_id, payout_mode, source, destinations) { 
        obj['token_id'] = token_id;
        obj['payout_mode'] = payout_mode;
        obj['source'] = source;
        obj['destinations'] = destinations;
    }

    /**
     * Constructs a <code>EstimateBatchPayoutFeeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EstimateBatchPayoutFeeRequest} obj Optional instance to populate.
     * @return {module:model/EstimateBatchPayoutFeeRequest} The populated <code>EstimateBatchPayoutFeeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EstimateBatchPayoutFeeRequest();

            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('payout_mode')) {
                obj['payout_mode'] = PayoutMode.constructFromObject(data['payout_mode']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = PayoutSource.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('destinations')) {
                obj['destinations'] = ApiClient.convertToType(data['destinations'], [PayoutDestination]);
            }
            if (data.hasOwnProperty('rbf_type')) {
                obj['rbf_type'] = PayoutRbfType.constructFromObject(data['rbf_type']);
            }
            if (data.hasOwnProperty('replaced_payout_id')) {
                obj['replaced_payout_id'] = ApiClient.convertToType(data['replaced_payout_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EstimateBatchPayoutFeeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EstimateBatchPayoutFeeRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EstimateBatchPayoutFeeRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // validate the optional field `source`
        if (data['source']) { // data not null
          if (!!PayoutSource.validateJSON) {
            PayoutSource.validateJSON(data['source']);
          }
        }
        if (data['destinations']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['destinations'])) {
                throw new Error("Expected the field `destinations` to be an array in the JSON data but got " + data['destinations']);
            }
            // validate the optional field `destinations` (array)
            for (const item of data['destinations']) {
                PayoutDestination.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['replaced_payout_id'] && !(typeof data['replaced_payout_id'] === 'string' || data['replaced_payout_id'] instanceof String)) {
            throw new Error("Expected the field `replaced_payout_id` to be a primitive type in the JSON string but got " + data['replaced_payout_id']);
        }

        return true;
    }


}

EstimateBatchPayoutFeeRequest.RequiredProperties = ["token_id", "payout_mode", "source", "destinations"];

/**
 * The ID of the cryptocurrency used for payout. 
 * @member {String} token_id
 */
EstimateBatchPayoutFeeRequest.prototype['token_id'] = undefined;

/**
 * @member {module:model/PayoutMode} payout_mode
 */
EstimateBatchPayoutFeeRequest.prototype['payout_mode'] = undefined;

/**
 * @member {module:model/PayoutSource} source
 */
EstimateBatchPayoutFeeRequest.prototype['source'] = undefined;

/**
 * The destinations of the payout.
 * @member {Array.<module:model/PayoutDestination>} destinations
 */
EstimateBatchPayoutFeeRequest.prototype['destinations'] = undefined;

/**
 * @member {module:model/PayoutRbfType} rbf_type
 */
EstimateBatchPayoutFeeRequest.prototype['rbf_type'] = undefined;

/**
 * The ID of the payout that this payout replaced.
 * @member {String} replaced_payout_id
 */
EstimateBatchPayoutFeeRequest.prototype['replaced_payout_id'] = undefined;






export default EstimateBatchPayoutFeeRequest;

