/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import KyaRiskDetail from './KyaRiskDetail';
import KyaRiskLevel from './KyaRiskLevel';

/**
 * The KyaRiskAssessment model module.
 * @module model/KyaRiskAssessment
 */
class KyaRiskAssessment {
    /**
     * Constructs a new <code>KyaRiskAssessment</code>.
     * The risk assessment information for the screened address. Only returned when status is &#39;Screened&#39;.
     * @alias module:model/KyaRiskAssessment
     * @param level {module:model/KyaRiskLevel} 
     */
    constructor(level) { 
        
        KyaRiskAssessment.initialize(this, level);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, level) { 
        obj['level'] = level;
    }

    /**
     * Constructs a <code>KyaRiskAssessment</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KyaRiskAssessment} obj Optional instance to populate.
     * @return {module:model/KyaRiskAssessment} The populated <code>KyaRiskAssessment</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KyaRiskAssessment();

            if (data.hasOwnProperty('level')) {
                obj['level'] = KyaRiskLevel.constructFromObject(data['level']);
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = ApiClient.convertToType(data['summary'], 'String');
            }
            if (data.hasOwnProperty('details')) {
                obj['details'] = ApiClient.convertToType(data['details'], [KyaRiskDetail]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>KyaRiskAssessment</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>KyaRiskAssessment</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of KyaRiskAssessment.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['summary'] && !(typeof data['summary'] === 'string' || data['summary'] instanceof String)) {
            throw new Error("Expected the field `summary` to be a primitive type in the JSON string but got " + data['summary']);
        }
        if (data['details']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['details'])) {
                throw new Error("Expected the field `details` to be an array in the JSON data but got " + data['details']);
            }
            // validate the optional field `details` (array)
            for (const item of data['details']) {
                KyaRiskDetail.validateJSON(item);
            };
        }

        return true;
    }


}

KyaRiskAssessment.RequiredProperties = ["level"];

/**
 * @member {module:model/KyaRiskLevel} level
 */
KyaRiskAssessment.prototype['level'] = undefined;

/**
 * A brief summary of the risk assessment.
 * @member {String} summary
 */
KyaRiskAssessment.prototype['summary'] = undefined;

/**
 * Detailed risk category assessments.
 * @member {Array.<module:model/KyaRiskDetail>} details
 */
KyaRiskAssessment.prototype['details'] = undefined;






export default KyaRiskAssessment;

