/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CounterpartyWalletAddressDetail from './CounterpartyWalletAddressDetail';
import Pagination from './Pagination';

/**
 * The ListCounterpartyEntries200Response model module.
 * @module model/ListCounterpartyEntries200Response
 */
class ListCounterpartyEntries200Response {
    /**
     * Constructs a new <code>ListCounterpartyEntries200Response</code>.
     * @alias module:model/ListCounterpartyEntries200Response
     */
    constructor() { 
        
        ListCounterpartyEntries200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ListCounterpartyEntries200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ListCounterpartyEntries200Response} obj Optional instance to populate.
     * @return {module:model/ListCounterpartyEntries200Response} The populated <code>ListCounterpartyEntries200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ListCounterpartyEntries200Response();

            if (data.hasOwnProperty('wallet_addresses')) {
                obj['wallet_addresses'] = ApiClient.convertToType(data['wallet_addresses'], [CounterpartyWalletAddressDetail]);
            }
            if (data.hasOwnProperty('pagination')) {
                obj['pagination'] = Pagination.constructFromObject(data['pagination']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ListCounterpartyEntries200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ListCounterpartyEntries200Response</code>.
     */
    static validateJSON(data) {
        if (data['wallet_addresses']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['wallet_addresses'])) {
                throw new Error("Expected the field `wallet_addresses` to be an array in the JSON data but got " + data['wallet_addresses']);
            }
            // validate the optional field `wallet_addresses` (array)
            for (const item of data['wallet_addresses']) {
                CounterpartyWalletAddressDetail.validateJSON(item);
            };
        }
        // validate the optional field `pagination`
        if (data['pagination']) { // data not null
          if (!!Pagination.validateJSON) {
            Pagination.validateJSON(data['pagination']);
          }
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/CounterpartyWalletAddressDetail>} wallet_addresses
 */
ListCounterpartyEntries200Response.prototype['wallet_addresses'] = undefined;

/**
 * @member {module:model/Pagination} pagination
 */
ListCounterpartyEntries200Response.prototype['pagination'] = undefined;






export default ListCounterpartyEntries200Response;

