/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OrderLinkBusinessInfoCustomExchangeRatesInner model module.
 * @module model/OrderLinkBusinessInfoCustomExchangeRatesInner
 */
class OrderLinkBusinessInfoCustomExchangeRatesInner {
    /**
     * Constructs a new <code>OrderLinkBusinessInfoCustomExchangeRatesInner</code>.
     * @alias module:model/OrderLinkBusinessInfoCustomExchangeRatesInner
     * @param token_id {String} The token ID.
     * @param exchange_rate {String} The exchange rate to use for this token.
     */
    constructor(token_id, exchange_rate) { 
        
        OrderLinkBusinessInfoCustomExchangeRatesInner.initialize(this, token_id, exchange_rate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, token_id, exchange_rate) { 
        obj['token_id'] = token_id;
        obj['exchange_rate'] = exchange_rate;
    }

    /**
     * Constructs a <code>OrderLinkBusinessInfoCustomExchangeRatesInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OrderLinkBusinessInfoCustomExchangeRatesInner} obj Optional instance to populate.
     * @return {module:model/OrderLinkBusinessInfoCustomExchangeRatesInner} The populated <code>OrderLinkBusinessInfoCustomExchangeRatesInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OrderLinkBusinessInfoCustomExchangeRatesInner();

            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('exchange_rate')) {
                obj['exchange_rate'] = ApiClient.convertToType(data['exchange_rate'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OrderLinkBusinessInfoCustomExchangeRatesInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OrderLinkBusinessInfoCustomExchangeRatesInner</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OrderLinkBusinessInfoCustomExchangeRatesInner.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // ensure the json data is a string
        if (data['exchange_rate'] && !(typeof data['exchange_rate'] === 'string' || data['exchange_rate'] instanceof String)) {
            throw new Error("Expected the field `exchange_rate` to be a primitive type in the JSON string but got " + data['exchange_rate']);
        }

        return true;
    }


}

OrderLinkBusinessInfoCustomExchangeRatesInner.RequiredProperties = ["token_id", "exchange_rate"];

/**
 * The token ID.
 * @member {String} token_id
 */
OrderLinkBusinessInfoCustomExchangeRatesInner.prototype['token_id'] = undefined;

/**
 * The exchange rate to use for this token.
 * @member {String} exchange_rate
 */
OrderLinkBusinessInfoCustomExchangeRatesInner.prototype['exchange_rate'] = undefined;






export default OrderLinkBusinessInfoCustomExchangeRatesInner;

