/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BankAccount from './BankAccount';
import PaymentPayoutDetail from './PaymentPayoutDetail';
import PaymentPayoutItemDetail from './PaymentPayoutItemDetail';
import PaymentPayoutStatus from './PaymentPayoutStatus';
import PayoutChannel from './PayoutChannel';
import WebhookEventDataType from './WebhookEventDataType';

/**
 * The PaymentPayoutEvent model module.
 * @module model/PaymentPayoutEvent
 */
class PaymentPayoutEvent {
    /**
     * Constructs a new <code>PaymentPayoutEvent</code>.
     * @alias module:model/PaymentPayoutEvent
     * @implements module:model/WebhookEventDataType
     * @implements module:model/PaymentPayoutDetail
     * @param data_type {module:model/PaymentPayoutEvent.DataTypeEnum}  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
     * @param payout_id {String} The payout ID generated by Cobo.
     * @param request_id {String} The request ID provided by you when creating the payout.
     * @param status {module:model/PaymentPayoutStatus} 
     */
    constructor(data_type, payout_id, request_id, status) { 
        WebhookEventDataType.initialize(this, data_type);PaymentPayoutDetail.initialize(this, payout_id, request_id, status);
        PaymentPayoutEvent.initialize(this, data_type, payout_id, request_id, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data_type, payout_id, request_id, status) { 
        obj['data_type'] = data_type;
        obj['payout_id'] = payout_id;
        obj['request_id'] = request_id;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>PaymentPayoutEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentPayoutEvent} obj Optional instance to populate.
     * @return {module:model/PaymentPayoutEvent} The populated <code>PaymentPayoutEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentPayoutEvent();
            WebhookEventDataType.constructFromObject(data, obj);
            PaymentPayoutDetail.constructFromObject(data, obj);

            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('payout_id')) {
                obj['payout_id'] = ApiClient.convertToType(data['payout_id'], 'String');
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentPayoutStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('payout_item_details')) {
                obj['payout_item_details'] = ApiClient.convertToType(data['payout_item_details'], [PaymentPayoutItemDetail]);
            }
            if (data.hasOwnProperty('created_timestamp')) {
                obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('updated_timestamp')) {
                obj['updated_timestamp'] = ApiClient.convertToType(data['updated_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('initiator')) {
                obj['initiator'] = ApiClient.convertToType(data['initiator'], 'String');
            }
            if (data.hasOwnProperty('payout_channel')) {
                obj['payout_channel'] = PayoutChannel.constructFromObject(data['payout_channel']);
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('actual_payout_amount')) {
                obj['actual_payout_amount'] = ApiClient.convertToType(data['actual_payout_amount'], 'String');
            }
            if (data.hasOwnProperty('bank_account')) {
                obj['bank_account'] = BankAccount.constructFromObject(data['bank_account']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentPayoutEvent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentPayoutEvent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentPayoutEvent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        // ensure the json data is a string
        if (data['payout_id'] && !(typeof data['payout_id'] === 'string' || data['payout_id'] instanceof String)) {
            throw new Error("Expected the field `payout_id` to be a primitive type in the JSON string but got " + data['payout_id']);
        }
        // ensure the json data is a string
        if (data['request_id'] && !(typeof data['request_id'] === 'string' || data['request_id'] instanceof String)) {
            throw new Error("Expected the field `request_id` to be a primitive type in the JSON string but got " + data['request_id']);
        }
        if (data['payout_item_details']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['payout_item_details'])) {
                throw new Error("Expected the field `payout_item_details` to be an array in the JSON data but got " + data['payout_item_details']);
            }
            // validate the optional field `payout_item_details` (array)
            for (const item of data['payout_item_details']) {
                PaymentPayoutItemDetail.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['initiator'] && !(typeof data['initiator'] === 'string' || data['initiator'] instanceof String)) {
            throw new Error("Expected the field `initiator` to be a primitive type in the JSON string but got " + data['initiator']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['actual_payout_amount'] && !(typeof data['actual_payout_amount'] === 'string' || data['actual_payout_amount'] instanceof String)) {
            throw new Error("Expected the field `actual_payout_amount` to be a primitive type in the JSON string but got " + data['actual_payout_amount']);
        }
        // validate the optional field `bank_account`
        if (data['bank_account']) { // data not null
          if (!!BankAccount.validateJSON) {
            BankAccount.validateJSON(data['bank_account']);
          }
        }

        return true;
    }


}

PaymentPayoutEvent.RequiredProperties = ["data_type", "payout_id", "request_id", "status"];

/**
 *  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
 * @member {module:model/PaymentPayoutEvent.DataTypeEnum} data_type
 */
PaymentPayoutEvent.prototype['data_type'] = undefined;

/**
 * The payout ID generated by Cobo.
 * @member {String} payout_id
 */
PaymentPayoutEvent.prototype['payout_id'] = undefined;

/**
 * The request ID provided by you when creating the payout.
 * @member {String} request_id
 */
PaymentPayoutEvent.prototype['request_id'] = undefined;

/**
 * @member {module:model/PaymentPayoutStatus} status
 */
PaymentPayoutEvent.prototype['status'] = undefined;

/**
 * @member {Array.<module:model/PaymentPayoutItemDetail>} payout_item_details
 */
PaymentPayoutEvent.prototype['payout_item_details'] = undefined;

/**
 * The created time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentPayoutEvent.prototype['created_timestamp'] = undefined;

/**
 * The updated time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentPayoutEvent.prototype['updated_timestamp'] = undefined;

/**
 * The initiator of this payout, usually the API key used to create the payout.
 * @member {String} initiator
 */
PaymentPayoutEvent.prototype['initiator'] = undefined;

/**
 * @member {module:model/PayoutChannel} payout_channel
 */
PaymentPayoutEvent.prototype['payout_channel'] = undefined;

/**
 * The fiat currency you will receive from the payout.
 * @member {String} currency
 */
PaymentPayoutEvent.prototype['currency'] = undefined;

/**
 * The total amount of cryptocurrency actually paid out for this payout. 
 * @member {String} actual_payout_amount
 */
PaymentPayoutEvent.prototype['actual_payout_amount'] = undefined;

/**
 * @member {module:model/BankAccount} bank_account
 */
PaymentPayoutEvent.prototype['bank_account'] = undefined;


// Implement WebhookEventDataType interface:
/**
 *  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
 * @member {module:model/WebhookEventDataType.DataTypeEnum} data_type
 */
WebhookEventDataType.prototype['data_type'] = undefined;
// Implement PaymentPayoutDetail interface:
/**
 * The payout ID generated by Cobo.
 * @member {String} payout_id
 */
PaymentPayoutDetail.prototype['payout_id'] = undefined;
/**
 * The request ID provided by you when creating the payout.
 * @member {String} request_id
 */
PaymentPayoutDetail.prototype['request_id'] = undefined;
/**
 * @member {module:model/PaymentPayoutStatus} status
 */
PaymentPayoutDetail.prototype['status'] = undefined;
/**
 * @member {Array.<module:model/PaymentPayoutItemDetail>} payout_item_details
 */
PaymentPayoutDetail.prototype['payout_item_details'] = undefined;
/**
 * The created time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentPayoutDetail.prototype['created_timestamp'] = undefined;
/**
 * The updated time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentPayoutDetail.prototype['updated_timestamp'] = undefined;
/**
 * The initiator of this payout, usually the API key used to create the payout.
 * @member {String} initiator
 */
PaymentPayoutDetail.prototype['initiator'] = undefined;
/**
 * @member {module:model/PayoutChannel} payout_channel
 */
PaymentPayoutDetail.prototype['payout_channel'] = undefined;
/**
 * The fiat currency you will receive from the payout.
 * @member {String} currency
 */
PaymentPayoutDetail.prototype['currency'] = undefined;
/**
 * The total amount of cryptocurrency actually paid out for this payout. 
 * @member {String} actual_payout_amount
 */
PaymentPayoutDetail.prototype['actual_payout_amount'] = undefined;
/**
 * @member {module:model/BankAccount} bank_account
 */
PaymentPayoutDetail.prototype['bank_account'] = undefined;



/**
 * Allowed values for the <code>data_type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentPayoutEvent['DataTypeEnum'] = {

    /**
     * value: "Transaction"
     * @const
     */
    "Transaction": "Transaction",

    /**
     * value: "TSSRequest"
     * @const
     */
    "TSSRequest": "TSSRequest",

    /**
     * value: "Addresses"
     * @const
     */
    "Addresses": "Addresses",

    /**
     * value: "WalletInfo"
     * @const
     */
    "WalletInfo": "WalletInfo",

    /**
     * value: "MPCVault"
     * @const
     */
    "MPCVault": "MPCVault",

    /**
     * value: "Chains"
     * @const
     */
    "Chains": "Chains",

    /**
     * value: "Tokens"
     * @const
     */
    "Tokens": "Tokens",

    /**
     * value: "TokenListing"
     * @const
     */
    "TokenListing": "TokenListing",

    /**
     * value: "PaymentOrder"
     * @const
     */
    "PaymentOrder": "PaymentOrder",

    /**
     * value: "PaymentRefund"
     * @const
     */
    "PaymentRefund": "PaymentRefund",

    /**
     * value: "PaymentSettlement"
     * @const
     */
    "PaymentSettlement": "PaymentSettlement",

    /**
     * value: "PaymentTransaction"
     * @const
     */
    "PaymentTransaction": "PaymentTransaction",

    /**
     * value: "PaymentAddressUpdate"
     * @const
     */
    "PaymentAddressUpdate": "PaymentAddressUpdate",

    /**
     * value: "PaymentPayout"
     * @const
     */
    "PaymentPayout": "PaymentPayout",

    /**
     * value: "BalanceUpdateInfo"
     * @const
     */
    "BalanceUpdateInfo": "BalanceUpdateInfo",

    /**
     * value: "SuspendedToken"
     * @const
     */
    "SuspendedToken": "SuspendedToken",

    /**
     * value: "ComplianceDisposition"
     * @const
     */
    "ComplianceDisposition": "ComplianceDisposition",

    /**
     * value: "ComplianceKytScreenings"
     * @const
     */
    "ComplianceKytScreenings": "ComplianceKytScreenings",

    /**
     * value: "ComplianceKyaScreenings"
     * @const
     */
    "ComplianceKyaScreenings": "ComplianceKyaScreenings",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default PaymentPayoutEvent;

