/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentBulkSend from './PaymentBulkSend';
import PaymentBulkSendExecutionMode from './PaymentBulkSendExecutionMode';
import PaymentBulkSendStatus from './PaymentBulkSendStatus';
import WebhookEventDataType from './WebhookEventDataType';

/**
 * The PaymentBulkSendEvent model module.
 * @module model/PaymentBulkSendEvent
 */
class PaymentBulkSendEvent {
    /**
     * Constructs a new <code>PaymentBulkSendEvent</code>.
     * @alias module:model/PaymentBulkSendEvent
     * @implements module:model/WebhookEventDataType
     * @implements module:model/PaymentBulkSend
     * @param data_type {module:model/PaymentBulkSendEvent.DataTypeEnum}  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `PaymentBulkSend`: The payment bulk send event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
     * @param bulk_send_id {String} The bulk send ID.
     * @param source_account {String} The source account from which the bulk send will be made. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. 
     * @param execution_mode {module:model/PaymentBulkSendExecutionMode} 
     * @param status {module:model/PaymentBulkSendStatus} 
     * @param created_timestamp {Number} The created time of the bulk send, represented as a UNIX timestamp in seconds.
     * @param updated_timestamp {Number} The updated time of the bulk send, represented as a UNIX timestamp in seconds.
     */
    constructor(data_type, bulk_send_id, source_account, execution_mode, status, created_timestamp, updated_timestamp) { 
        WebhookEventDataType.initialize(this, data_type);PaymentBulkSend.initialize(this, bulk_send_id, source_account, execution_mode, status, created_timestamp, updated_timestamp);
        PaymentBulkSendEvent.initialize(this, data_type, bulk_send_id, source_account, execution_mode, status, created_timestamp, updated_timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data_type, bulk_send_id, source_account, execution_mode, status, created_timestamp, updated_timestamp) { 
        obj['data_type'] = data_type;
        obj['bulk_send_id'] = bulk_send_id;
        obj['source_account'] = source_account;
        obj['execution_mode'] = execution_mode;
        obj['status'] = status;
        obj['created_timestamp'] = created_timestamp;
        obj['updated_timestamp'] = updated_timestamp;
    }

    /**
     * Constructs a <code>PaymentBulkSendEvent</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentBulkSendEvent} obj Optional instance to populate.
     * @return {module:model/PaymentBulkSendEvent} The populated <code>PaymentBulkSendEvent</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentBulkSendEvent();
            WebhookEventDataType.constructFromObject(data, obj);
            PaymentBulkSend.constructFromObject(data, obj);

            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('bulk_send_id')) {
                obj['bulk_send_id'] = ApiClient.convertToType(data['bulk_send_id'], 'String');
            }
            if (data.hasOwnProperty('source_account')) {
                obj['source_account'] = ApiClient.convertToType(data['source_account'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('execution_mode')) {
                obj['execution_mode'] = PaymentBulkSendExecutionMode.constructFromObject(data['execution_mode']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentBulkSendStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('created_timestamp')) {
                obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('updated_timestamp')) {
                obj['updated_timestamp'] = ApiClient.convertToType(data['updated_timestamp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentBulkSendEvent</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentBulkSendEvent</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentBulkSendEvent.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        // ensure the json data is a string
        if (data['bulk_send_id'] && !(typeof data['bulk_send_id'] === 'string' || data['bulk_send_id'] instanceof String)) {
            throw new Error("Expected the field `bulk_send_id` to be a primitive type in the JSON string but got " + data['bulk_send_id']);
        }
        // ensure the json data is a string
        if (data['source_account'] && !(typeof data['source_account'] === 'string' || data['source_account'] instanceof String)) {
            throw new Error("Expected the field `source_account` to be a primitive type in the JSON string but got " + data['source_account']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

PaymentBulkSendEvent.RequiredProperties = ["data_type", "bulk_send_id", "source_account", "execution_mode", "status", "created_timestamp", "updated_timestamp"];

/**
 *  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `PaymentBulkSend`: The payment bulk send event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
 * @member {module:model/PaymentBulkSendEvent.DataTypeEnum} data_type
 */
PaymentBulkSendEvent.prototype['data_type'] = undefined;

/**
 * The bulk send ID.
 * @member {String} bulk_send_id
 */
PaymentBulkSendEvent.prototype['bulk_send_id'] = undefined;

/**
 * The source account from which the bulk send will be made. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. 
 * @member {String} source_account
 */
PaymentBulkSendEvent.prototype['source_account'] = undefined;

/**
 * The description for the entire bulk send batch.
 * @member {String} description
 */
PaymentBulkSendEvent.prototype['description'] = undefined;

/**
 * @member {module:model/PaymentBulkSendExecutionMode} execution_mode
 */
PaymentBulkSendEvent.prototype['execution_mode'] = undefined;

/**
 * @member {module:model/PaymentBulkSendStatus} status
 */
PaymentBulkSendEvent.prototype['status'] = undefined;

/**
 * The created time of the bulk send, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentBulkSendEvent.prototype['created_timestamp'] = undefined;

/**
 * The updated time of the bulk send, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentBulkSendEvent.prototype['updated_timestamp'] = undefined;


// Implement WebhookEventDataType interface:
/**
 *  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The top-up address update event data. - `PaymentPayout`: The payment payout event data. - `PaymentBulkSend`: The payment bulk send event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The token suspension event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data. - `ComplianceKyaScreenings`: The compliance KYA screenings event data.
 * @member {module:model/WebhookEventDataType.DataTypeEnum} data_type
 */
WebhookEventDataType.prototype['data_type'] = undefined;
// Implement PaymentBulkSend interface:
/**
 * The bulk send ID.
 * @member {String} bulk_send_id
 */
PaymentBulkSend.prototype['bulk_send_id'] = undefined;
/**
 * The source account from which the bulk send will be made. - If the source account is a merchant account, provide the merchant's ID (e.g., \"M1001\"). - If the source account is the developer account, use the string `\"developer\"`. 
 * @member {String} source_account
 */
PaymentBulkSend.prototype['source_account'] = undefined;
/**
 * The description for the entire bulk send batch.
 * @member {String} description
 */
PaymentBulkSend.prototype['description'] = undefined;
/**
 * @member {module:model/PaymentBulkSendExecutionMode} execution_mode
 */
PaymentBulkSend.prototype['execution_mode'] = undefined;
/**
 * @member {module:model/PaymentBulkSendStatus} status
 */
PaymentBulkSend.prototype['status'] = undefined;
/**
 * The created time of the bulk send, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentBulkSend.prototype['created_timestamp'] = undefined;
/**
 * The updated time of the bulk send, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentBulkSend.prototype['updated_timestamp'] = undefined;



/**
 * Allowed values for the <code>data_type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentBulkSendEvent['DataTypeEnum'] = {

    /**
     * value: "Transaction"
     * @const
     */
    "Transaction": "Transaction",

    /**
     * value: "TSSRequest"
     * @const
     */
    "TSSRequest": "TSSRequest",

    /**
     * value: "Addresses"
     * @const
     */
    "Addresses": "Addresses",

    /**
     * value: "WalletInfo"
     * @const
     */
    "WalletInfo": "WalletInfo",

    /**
     * value: "MPCVault"
     * @const
     */
    "MPCVault": "MPCVault",

    /**
     * value: "Chains"
     * @const
     */
    "Chains": "Chains",

    /**
     * value: "Tokens"
     * @const
     */
    "Tokens": "Tokens",

    /**
     * value: "TokenListing"
     * @const
     */
    "TokenListing": "TokenListing",

    /**
     * value: "PaymentOrder"
     * @const
     */
    "PaymentOrder": "PaymentOrder",

    /**
     * value: "PaymentRefund"
     * @const
     */
    "PaymentRefund": "PaymentRefund",

    /**
     * value: "PaymentSettlement"
     * @const
     */
    "PaymentSettlement": "PaymentSettlement",

    /**
     * value: "PaymentTransaction"
     * @const
     */
    "PaymentTransaction": "PaymentTransaction",

    /**
     * value: "PaymentAddressUpdate"
     * @const
     */
    "PaymentAddressUpdate": "PaymentAddressUpdate",

    /**
     * value: "PaymentPayout"
     * @const
     */
    "PaymentPayout": "PaymentPayout",

    /**
     * value: "PaymentBulkSend"
     * @const
     */
    "PaymentBulkSend": "PaymentBulkSend",

    /**
     * value: "BalanceUpdateInfo"
     * @const
     */
    "BalanceUpdateInfo": "BalanceUpdateInfo",

    /**
     * value: "SuspendedToken"
     * @const
     */
    "SuspendedToken": "SuspendedToken",

    /**
     * value: "ComplianceDisposition"
     * @const
     */
    "ComplianceDisposition": "ComplianceDisposition",

    /**
     * value: "ComplianceKytScreenings"
     * @const
     */
    "ComplianceKytScreenings": "ComplianceKytScreenings",

    /**
     * value: "ComplianceKyaScreenings"
     * @const
     */
    "ComplianceKyaScreenings": "ComplianceKyaScreenings",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default PaymentBulkSendEvent;

