/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentEstimateFee from './PaymentEstimateFee';
import PaymentFeeType from './PaymentFeeType';

/**
 * The PaymentEstimateFeeRequest model module.
 * @module model/PaymentEstimateFeeRequest
 */
class PaymentEstimateFeeRequest {
    /**
     * Constructs a new <code>PaymentEstimateFeeRequest</code>.
     * @alias module:model/PaymentEstimateFeeRequest
     * @param estimate_fees {Array.<module:model/PaymentEstimateFee>} A list of token IDs and amounts for which fees will be calculated.
     */
    constructor(estimate_fees) { 
        
        PaymentEstimateFeeRequest.initialize(this, estimate_fees);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, estimate_fees) { 
        obj['estimate_fees'] = estimate_fees;
    }

    /**
     * Constructs a <code>PaymentEstimateFeeRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentEstimateFeeRequest} obj Optional instance to populate.
     * @return {module:model/PaymentEstimateFeeRequest} The populated <code>PaymentEstimateFeeRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentEstimateFeeRequest();

            if (data.hasOwnProperty('fee_type')) {
                obj['fee_type'] = PaymentFeeType.constructFromObject(data['fee_type']);
            }
            if (data.hasOwnProperty('estimate_fees')) {
                obj['estimate_fees'] = ApiClient.convertToType(data['estimate_fees'], [PaymentEstimateFee]);
            }
            if (data.hasOwnProperty('recipient_token_id')) {
                obj['recipient_token_id'] = ApiClient.convertToType(data['recipient_token_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentEstimateFeeRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentEstimateFeeRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentEstimateFeeRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['estimate_fees']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['estimate_fees'])) {
                throw new Error("Expected the field `estimate_fees` to be an array in the JSON data but got " + data['estimate_fees']);
            }
            // validate the optional field `estimate_fees` (array)
            for (const item of data['estimate_fees']) {
                PaymentEstimateFee.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['recipient_token_id'] && !(typeof data['recipient_token_id'] === 'string' || data['recipient_token_id'] instanceof String)) {
            throw new Error("Expected the field `recipient_token_id` to be a primitive type in the JSON string but got " + data['recipient_token_id']);
        }

        return true;
    }


}

PaymentEstimateFeeRequest.RequiredProperties = ["estimate_fees"];

/**
 * @member {module:model/PaymentFeeType} fee_type
 */
PaymentEstimateFeeRequest.prototype['fee_type'] = undefined;

/**
 * A list of token IDs and amounts for which fees will be calculated.
 * @member {Array.<module:model/PaymentEstimateFee>} estimate_fees
 */
PaymentEstimateFeeRequest.prototype['estimate_fees'] = undefined;

/**
 * The token ID that the recipient will receive. Required only when `fee_type` is `CryptoPayoutBridge`.
 * @member {String} recipient_token_id
 */
PaymentEstimateFeeRequest.prototype['recipient_token_id'] = undefined;






export default PaymentEstimateFeeRequest;

