/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentSubscriptionActionType from './PaymentSubscriptionActionType';

/**
 * The PaymentSubscribeAndChargeSubscriptionActionData model module.
 * @module model/PaymentSubscribeAndChargeSubscriptionActionData
 */
class PaymentSubscribeAndChargeSubscriptionActionData {
    /**
     * Constructs a new <code>PaymentSubscribeAndChargeSubscriptionActionData</code>.
     * @alias module:model/PaymentSubscribeAndChargeSubscriptionActionData
     * @param action_type {module:model/PaymentSubscriptionActionType} 
     * @param subscription_id {String} The subscription id in cobo.
     * @param charge_amount {String} The subscription crypto amount, less than subscription plan amount. 
     * @param signature {String} The signature for transaction. charge action is not required.
     * @param deadline {Number} The signature deadline for transaction. charge action is not required.
     */
    constructor(action_type, subscription_id, charge_amount, signature, deadline) { 
        
        PaymentSubscribeAndChargeSubscriptionActionData.initialize(this, action_type, subscription_id, charge_amount, signature, deadline);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action_type, subscription_id, charge_amount, signature, deadline) { 
        obj['action_type'] = action_type;
        obj['subscription_id'] = subscription_id;
        obj['charge_amount'] = charge_amount;
        obj['signature'] = signature;
        obj['deadline'] = deadline;
    }

    /**
     * Constructs a <code>PaymentSubscribeAndChargeSubscriptionActionData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentSubscribeAndChargeSubscriptionActionData} obj Optional instance to populate.
     * @return {module:model/PaymentSubscribeAndChargeSubscriptionActionData} The populated <code>PaymentSubscribeAndChargeSubscriptionActionData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentSubscribeAndChargeSubscriptionActionData();

            if (data.hasOwnProperty('action_type')) {
                obj['action_type'] = PaymentSubscriptionActionType.constructFromObject(data['action_type']);
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
            if (data.hasOwnProperty('charge_amount')) {
                obj['charge_amount'] = ApiClient.convertToType(data['charge_amount'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentSubscribeAndChargeSubscriptionActionData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentSubscribeAndChargeSubscriptionActionData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentSubscribeAndChargeSubscriptionActionData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['subscription_id'] && !(typeof data['subscription_id'] === 'string' || data['subscription_id'] instanceof String)) {
            throw new Error("Expected the field `subscription_id` to be a primitive type in the JSON string but got " + data['subscription_id']);
        }
        // ensure the json data is a string
        if (data['charge_amount'] && !(typeof data['charge_amount'] === 'string' || data['charge_amount'] instanceof String)) {
            throw new Error("Expected the field `charge_amount` to be a primitive type in the JSON string but got " + data['charge_amount']);
        }
        // ensure the json data is a string
        if (data['signature'] && !(typeof data['signature'] === 'string' || data['signature'] instanceof String)) {
            throw new Error("Expected the field `signature` to be a primitive type in the JSON string but got " + data['signature']);
        }

        return true;
    }


}

PaymentSubscribeAndChargeSubscriptionActionData.RequiredProperties = ["action_type", "subscription_id", "charge_amount", "signature", "deadline"];

/**
 * @member {module:model/PaymentSubscriptionActionType} action_type
 */
PaymentSubscribeAndChargeSubscriptionActionData.prototype['action_type'] = undefined;

/**
 * The subscription id in cobo.
 * @member {String} subscription_id
 */
PaymentSubscribeAndChargeSubscriptionActionData.prototype['subscription_id'] = undefined;

/**
 * The subscription crypto amount, less than subscription plan amount. 
 * @member {String} charge_amount
 */
PaymentSubscribeAndChargeSubscriptionActionData.prototype['charge_amount'] = undefined;

/**
 * The signature for transaction. charge action is not required.
 * @member {String} signature
 */
PaymentSubscribeAndChargeSubscriptionActionData.prototype['signature'] = undefined;

/**
 * The signature deadline for transaction. charge action is not required.
 * @member {Number} deadline
 */
PaymentSubscribeAndChargeSubscriptionActionData.prototype['deadline'] = undefined;






export default PaymentSubscribeAndChargeSubscriptionActionData;

