/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentBaseSubscriptionActionData from './PaymentBaseSubscriptionActionData';
import PaymentSubscriptionActionType from './PaymentSubscriptionActionType';

/**
 * The PaymentExtendPeriodSubscriptionActionData model module.
 * @module model/PaymentExtendPeriodSubscriptionActionData
 */
class PaymentExtendPeriodSubscriptionActionData {
    /**
     * Constructs a new <code>PaymentExtendPeriodSubscriptionActionData</code>.
     * @alias module:model/PaymentExtendPeriodSubscriptionActionData
     * @implements module:model/PaymentBaseSubscriptionActionData
     * @param action_type {module:model/PaymentSubscriptionActionType} 
     * @param subscription_id {String} The subscription id in cobo.
     * @param signature {String} The signature for transaction.
     */
    constructor(action_type, subscription_id, signature) { 
        PaymentBaseSubscriptionActionData.initialize(this, action_type, subscription_id, signature);
        PaymentExtendPeriodSubscriptionActionData.initialize(this, action_type, subscription_id, signature);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action_type, subscription_id, signature) { 
        obj['action_type'] = action_type;
        obj['subscription_id'] = subscription_id;
        obj['signature'] = signature;
    }

    /**
     * Constructs a <code>PaymentExtendPeriodSubscriptionActionData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentExtendPeriodSubscriptionActionData} obj Optional instance to populate.
     * @return {module:model/PaymentExtendPeriodSubscriptionActionData} The populated <code>PaymentExtendPeriodSubscriptionActionData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentExtendPeriodSubscriptionActionData();
            PaymentBaseSubscriptionActionData.constructFromObject(data, obj);

            if (data.hasOwnProperty('periods')) {
                obj['periods'] = ApiClient.convertToType(data['periods'], 'Number');
            }
            if (data.hasOwnProperty('action_type')) {
                obj['action_type'] = PaymentSubscriptionActionType.constructFromObject(data['action_type']);
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentExtendPeriodSubscriptionActionData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentExtendPeriodSubscriptionActionData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentExtendPeriodSubscriptionActionData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['subscription_id'] && !(typeof data['subscription_id'] === 'string' || data['subscription_id'] instanceof String)) {
            throw new Error("Expected the field `subscription_id` to be a primitive type in the JSON string but got " + data['subscription_id']);
        }
        // ensure the json data is a string
        if (data['signature'] && !(typeof data['signature'] === 'string' || data['signature'] instanceof String)) {
            throw new Error("Expected the field `signature` to be a primitive type in the JSON string but got " + data['signature']);
        }

        return true;
    }


}

PaymentExtendPeriodSubscriptionActionData.RequiredProperties = ["action_type", "subscription_id", "signature"];

/**
 * The periods needed updated.
 * @member {Number} periods
 */
PaymentExtendPeriodSubscriptionActionData.prototype['periods'] = undefined;

/**
 * @member {module:model/PaymentSubscriptionActionType} action_type
 */
PaymentExtendPeriodSubscriptionActionData.prototype['action_type'] = undefined;

/**
 * The subscription id in cobo.
 * @member {String} subscription_id
 */
PaymentExtendPeriodSubscriptionActionData.prototype['subscription_id'] = undefined;

/**
 * The signature for transaction.
 * @member {String} signature
 */
PaymentExtendPeriodSubscriptionActionData.prototype['signature'] = undefined;


// Implement PaymentBaseSubscriptionActionData interface:
/**
 * @member {module:model/PaymentSubscriptionActionType} action_type
 */
PaymentBaseSubscriptionActionData.prototype['action_type'] = undefined;
/**
 * The subscription id in cobo.
 * @member {String} subscription_id
 */
PaymentBaseSubscriptionActionData.prototype['subscription_id'] = undefined;
/**
 * The signature for transaction.
 * @member {String} signature
 */
PaymentBaseSubscriptionActionData.prototype['signature'] = undefined;




export default PaymentExtendPeriodSubscriptionActionData;

