/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BankAccount from './BankAccount';
import PaymentPayoutItem from './PaymentPayoutItem';
import PaymentPayoutStatus from './PaymentPayoutStatus';
import PayoutChannel from './PayoutChannel';

/**
 * The PaymentPayout model module.
 * @module model/PaymentPayout
 */
class PaymentPayout {
    /**
     * Constructs a new <code>PaymentPayout</code>.
     * @alias module:model/PaymentPayout
     * @param payout_id {String} The payout ID generated by Cobo.
     * @param request_id {String} The request ID provided by you when creating the payout.
     * @param payout_channel {module:model/PayoutChannel} 
     * @param status {module:model/PaymentPayoutStatus} 
     */
    constructor(payout_id, request_id, payout_channel, status) { 
        
        PaymentPayout.initialize(this, payout_id, request_id, payout_channel, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, payout_id, request_id, payout_channel, status) { 
        obj['payout_id'] = payout_id;
        obj['request_id'] = request_id;
        obj['payout_channel'] = payout_channel;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>PaymentPayout</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentPayout} obj Optional instance to populate.
     * @return {module:model/PaymentPayout} The populated <code>PaymentPayout</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentPayout();

            if (data.hasOwnProperty('payout_id')) {
                obj['payout_id'] = ApiClient.convertToType(data['payout_id'], 'String');
            }
            if (data.hasOwnProperty('request_id')) {
                obj['request_id'] = ApiClient.convertToType(data['request_id'], 'String');
            }
            if (data.hasOwnProperty('payout_channel')) {
                obj['payout_channel'] = PayoutChannel.constructFromObject(data['payout_channel']);
            }
            if (data.hasOwnProperty('payout_items')) {
                obj['payout_items'] = ApiClient.convertToType(data['payout_items'], [PaymentPayoutItem]);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentPayoutStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('created_timestamp')) {
                obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('updated_timestamp')) {
                obj['updated_timestamp'] = ApiClient.convertToType(data['updated_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('initiator')) {
                obj['initiator'] = ApiClient.convertToType(data['initiator'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('actual_payout_amount')) {
                obj['actual_payout_amount'] = ApiClient.convertToType(data['actual_payout_amount'], 'String');
            }
            if (data.hasOwnProperty('bank_account')) {
                obj['bank_account'] = BankAccount.constructFromObject(data['bank_account']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentPayout</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentPayout</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentPayout.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['payout_id'] && !(typeof data['payout_id'] === 'string' || data['payout_id'] instanceof String)) {
            throw new Error("Expected the field `payout_id` to be a primitive type in the JSON string but got " + data['payout_id']);
        }
        // ensure the json data is a string
        if (data['request_id'] && !(typeof data['request_id'] === 'string' || data['request_id'] instanceof String)) {
            throw new Error("Expected the field `request_id` to be a primitive type in the JSON string but got " + data['request_id']);
        }
        if (data['payout_items']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['payout_items'])) {
                throw new Error("Expected the field `payout_items` to be an array in the JSON data but got " + data['payout_items']);
            }
            // validate the optional field `payout_items` (array)
            for (const item of data['payout_items']) {
                PaymentPayoutItem.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['initiator'] && !(typeof data['initiator'] === 'string' || data['initiator'] instanceof String)) {
            throw new Error("Expected the field `initiator` to be a primitive type in the JSON string but got " + data['initiator']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['actual_payout_amount'] && !(typeof data['actual_payout_amount'] === 'string' || data['actual_payout_amount'] instanceof String)) {
            throw new Error("Expected the field `actual_payout_amount` to be a primitive type in the JSON string but got " + data['actual_payout_amount']);
        }
        // validate the optional field `bank_account`
        if (data['bank_account']) { // data not null
          if (!!BankAccount.validateJSON) {
            BankAccount.validateJSON(data['bank_account']);
          }
        }

        return true;
    }


}

PaymentPayout.RequiredProperties = ["payout_id", "request_id", "payout_channel", "status"];

/**
 * The payout ID generated by Cobo.
 * @member {String} payout_id
 */
PaymentPayout.prototype['payout_id'] = undefined;

/**
 * The request ID provided by you when creating the payout.
 * @member {String} request_id
 */
PaymentPayout.prototype['request_id'] = undefined;

/**
 * @member {module:model/PayoutChannel} payout_channel
 */
PaymentPayout.prototype['payout_channel'] = undefined;

/**
 * @member {Array.<module:model/PaymentPayoutItem>} payout_items
 */
PaymentPayout.prototype['payout_items'] = undefined;

/**
 * @member {module:model/PaymentPayoutStatus} status
 */
PaymentPayout.prototype['status'] = undefined;

/**
 * The created time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentPayout.prototype['created_timestamp'] = undefined;

/**
 * The updated time of the payout, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentPayout.prototype['updated_timestamp'] = undefined;

/**
 * The initiator of this payout, usually the API key used to create the payout.
 * @member {String} initiator
 */
PaymentPayout.prototype['initiator'] = undefined;

/**
 * The fiat currency you will receive from the payout.
 * @member {String} currency
 */
PaymentPayout.prototype['currency'] = undefined;

/**
 * The total amount of cryptocurrency actually paid out for this payout. 
 * @member {String} actual_payout_amount
 */
PaymentPayout.prototype['actual_payout_amount'] = undefined;

/**
 * @member {module:model/BankAccount} bank_account
 */
PaymentPayout.prototype['bank_account'] = undefined;






export default PaymentPayout;

