/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BridgingFee from './BridgingFee';
import CommissionFee from './CommissionFee';
import PaymentPayoutItemStatus from './PaymentPayoutItemStatus';
import PaymentTransaction from './PaymentTransaction';

/**
 * The PaymentPayoutItem model module.
 * @module model/PaymentPayoutItem
 */
class PaymentPayoutItem {
    /**
     * Constructs a new <code>PaymentPayoutItem</code>.
     * @alias module:model/PaymentPayoutItem
     * @param payout_item_id {String} The payout item ID generated by Cobo.
     * @param payout_id {String} The payout ID generated by Cobo.
     * @param amount {String} The payout item token_id amount. 
     * @param status {module:model/PaymentPayoutItemStatus} 
     * @param source_account {String} 
     */
    constructor(payout_item_id, payout_id, amount, status, source_account) { 
        
        PaymentPayoutItem.initialize(this, payout_item_id, payout_id, amount, status, source_account);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, payout_item_id, payout_id, amount, status, source_account) { 
        obj['payout_item_id'] = payout_item_id;
        obj['payout_id'] = payout_id;
        obj['amount'] = amount;
        obj['status'] = status;
        obj['source_account'] = source_account;
    }

    /**
     * Constructs a <code>PaymentPayoutItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentPayoutItem} obj Optional instance to populate.
     * @return {module:model/PaymentPayoutItem} The populated <code>PaymentPayoutItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentPayoutItem();

            if (data.hasOwnProperty('payout_item_id')) {
                obj['payout_item_id'] = ApiClient.convertToType(data['payout_item_id'], 'String');
            }
            if (data.hasOwnProperty('payout_id')) {
                obj['payout_id'] = ApiClient.convertToType(data['payout_id'], 'String');
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('chain_id')) {
                obj['chain_id'] = ApiClient.convertToType(data['chain_id'], 'String');
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentPayoutItemStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('source_account')) {
                obj['source_account'] = ApiClient.convertToType(data['source_account'], 'String');
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [PaymentTransaction]);
            }
            if (data.hasOwnProperty('created_timestamp')) {
                obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('updated_timestamp')) {
                obj['updated_timestamp'] = ApiClient.convertToType(data['updated_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('crypto_address_id')) {
                obj['crypto_address_id'] = ApiClient.convertToType(data['crypto_address_id'], 'String');
            }
            if (data.hasOwnProperty('crypto_address')) {
                obj['crypto_address'] = ApiClient.convertToType(data['crypto_address'], 'String');
            }
            if (data.hasOwnProperty('commission_fee')) {
                obj['commission_fee'] = CommissionFee.constructFromObject(data['commission_fee']);
            }
            if (data.hasOwnProperty('bridging_fee')) {
                obj['bridging_fee'] = BridgingFee.constructFromObject(data['bridging_fee']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentPayoutItem</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentPayoutItem</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentPayoutItem.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['payout_item_id'] && !(typeof data['payout_item_id'] === 'string' || data['payout_item_id'] instanceof String)) {
            throw new Error("Expected the field `payout_item_id` to be a primitive type in the JSON string but got " + data['payout_item_id']);
        }
        // ensure the json data is a string
        if (data['payout_id'] && !(typeof data['payout_id'] === 'string' || data['payout_id'] instanceof String)) {
            throw new Error("Expected the field `payout_id` to be a primitive type in the JSON string but got " + data['payout_id']);
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // ensure the json data is a string
        if (data['chain_id'] && !(typeof data['chain_id'] === 'string' || data['chain_id'] instanceof String)) {
            throw new Error("Expected the field `chain_id` to be a primitive type in the JSON string but got " + data['chain_id']);
        }
        // ensure the json data is a string
        if (data['amount'] && !(typeof data['amount'] === 'string' || data['amount'] instanceof String)) {
            throw new Error("Expected the field `amount` to be a primitive type in the JSON string but got " + data['amount']);
        }
        // ensure the json data is a string
        if (data['source_account'] && !(typeof data['source_account'] === 'string' || data['source_account'] instanceof String)) {
            throw new Error("Expected the field `source_account` to be a primitive type in the JSON string but got " + data['source_account']);
        }
        if (data['transactions']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['transactions'])) {
                throw new Error("Expected the field `transactions` to be an array in the JSON data but got " + data['transactions']);
            }
            // validate the optional field `transactions` (array)
            for (const item of data['transactions']) {
                PaymentTransaction.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['crypto_address_id'] && !(typeof data['crypto_address_id'] === 'string' || data['crypto_address_id'] instanceof String)) {
            throw new Error("Expected the field `crypto_address_id` to be a primitive type in the JSON string but got " + data['crypto_address_id']);
        }
        // ensure the json data is a string
        if (data['crypto_address'] && !(typeof data['crypto_address'] === 'string' || data['crypto_address'] instanceof String)) {
            throw new Error("Expected the field `crypto_address` to be a primitive type in the JSON string but got " + data['crypto_address']);
        }
        // validate the optional field `commission_fee`
        if (data['commission_fee']) { // data not null
          if (!!CommissionFee.validateJSON) {
            CommissionFee.validateJSON(data['commission_fee']);
          }
        }
        // validate the optional field `bridging_fee`
        if (data['bridging_fee']) { // data not null
          if (!!BridgingFee.validateJSON) {
            BridgingFee.validateJSON(data['bridging_fee']);
          }
        }

        return true;
    }


}

PaymentPayoutItem.RequiredProperties = ["payout_item_id", "payout_id", "amount", "status", "source_account"];

/**
 * The payout item ID generated by Cobo.
 * @member {String} payout_item_id
 */
PaymentPayoutItem.prototype['payout_item_id'] = undefined;

/**
 * The payout ID generated by Cobo.
 * @member {String} payout_id
 */
PaymentPayoutItem.prototype['payout_id'] = undefined;

/**
 * The token id of the payout item.
 * @member {String} token_id
 */
PaymentPayoutItem.prototype['token_id'] = undefined;

/**
 * The ID of the blockchain network on which the payout item occurred.
 * @member {String} chain_id
 */
PaymentPayoutItem.prototype['chain_id'] = undefined;

/**
 * The payout item token_id amount. 
 * @member {String} amount
 */
PaymentPayoutItem.prototype['amount'] = undefined;

/**
 * @member {module:model/PaymentPayoutItemStatus} status
 */
PaymentPayoutItem.prototype['status'] = undefined;

/**
 * @member {String} source_account
 */
PaymentPayoutItem.prototype['source_account'] = undefined;

/**
 * An array of transactions associated with this payout item request. Each transaction represents a separate blockchain operation related to the payout item process.
 * @member {Array.<module:model/PaymentTransaction>} transactions
 */
PaymentPayoutItem.prototype['transactions'] = undefined;

/**
 * The created time of the payout item, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentPayoutItem.prototype['created_timestamp'] = undefined;

/**
 * The updated time of the payout item, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentPayoutItem.prototype['updated_timestamp'] = undefined;

/**
 * Unique identifier for the pre-approved crypto address, used to reference the address securely in requests.
 * @member {String} crypto_address_id
 */
PaymentPayoutItem.prototype['crypto_address_id'] = undefined;

/**
 * The actual blockchain address to which funds were transferred.
 * @member {String} crypto_address
 */
PaymentPayoutItem.prototype['crypto_address'] = undefined;

/**
 * @member {module:model/CommissionFee} commission_fee
 */
PaymentPayoutItem.prototype['commission_fee'] = undefined;

/**
 * @member {module:model/BridgingFee} bridging_fee
 */
PaymentPayoutItem.prototype['bridging_fee'] = undefined;






export default PaymentPayoutItem;

