/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentFeeType.
* @enum {}
* @readonly
*/
export default class PaymentFeeType {
    
        /**
         * value: "Order"
         * @const
         */
        "Order" = "Order";

    
        /**
         * value: "Refund"
         * @const
         */
        "Refund" = "Refund";

    
        /**
         * value: "CryptoSettlement"
         * @const
         */
        "CryptoSettlement" = "CryptoSettlement";

    
        /**
         * value: "OffRampSettlement"
         * @const
         */
        "OffRampSettlement" = "OffRampSettlement";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>PaymentFeeType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentFeeType} The enum <code>PaymentFeeType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

