/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PaymentBulkSendItemValidationStatus.
* @enum {}
* @readonly
*/
export default class PaymentBulkSendItemValidationStatus {
    
        /**
         * value: "Pending"
         * @const
         */
        "Pending" = "Pending";

    
        /**
         * value: "Validated"
         * @const
         */
        "Validated" = "Validated";

    
        /**
         * value: "ValidationFailed"
         * @const
         */
        "ValidationFailed" = "ValidationFailed";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>PaymentBulkSendItemValidationStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PaymentBulkSendItemValidationStatus} The enum <code>PaymentBulkSendItemValidationStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

