/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentSubscription from './PaymentSubscription';
import PaymentSubscriptionPeriodType from './PaymentSubscriptionPeriodType';
import PaymentSubscriptionStatus from './PaymentSubscriptionStatus';
import WebhookEventDataType from './WebhookEventDataType';

/**
 * The PaymentSubscriptionUpdateEventData model module.
 * @module model/PaymentSubscriptionUpdateEventData
 */
class PaymentSubscriptionUpdateEventData {
    /**
     * Constructs a new <code>PaymentSubscriptionUpdateEventData</code>.
     * @alias module:model/PaymentSubscriptionUpdateEventData
     * @implements module:model/WebhookEventDataType
     * @implements module:model/PaymentSubscription
     * @param data_type {module:model/PaymentSubscriptionUpdateEventData.DataTypeEnum}  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The payment address update event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The suspended token event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data.
     * @param plan_id {String} The plan id in cobo.
     * @param subscription_id {String} The subscription id in cobo.
     * @param merchant_id {String} The merchant id in cobo.
     * @param merchant_address {String} The merchant address in cobo.
     * @param user_address {String} The user address in subscription.
     * @param token_id {String} The token_id in subscription.
     * @param start_time {Number} The subscription start timestamp.
     * @param expiration_time {Number} The subscription expired timestamp.
     * @param charges_made {Number} The subscription charge times.
     * @param period_type {module:model/PaymentSubscriptionPeriodType} 
     * @param periods {Number} 
     * @param interval {Number} The subscription charge interval.
     * @param status {module:model/PaymentSubscriptionStatus} 
     * @param created_timestamp {Number} The created time of the subscription, represented as a UNIX timestamp in seconds.
     * @param updated_timestamp {Number} The updated time of the subscription, represented as a UNIX timestamp in seconds.
     */
    constructor(data_type, plan_id, subscription_id, merchant_id, merchant_address, user_address, token_id, start_time, expiration_time, charges_made, period_type, periods, interval, status, created_timestamp, updated_timestamp) { 
        WebhookEventDataType.initialize(this, data_type);PaymentSubscription.initialize(this, plan_id, subscription_id, merchant_id, merchant_address, user_address, token_id, start_time, expiration_time, charges_made, period_type, periods, interval, status, created_timestamp, updated_timestamp);
        PaymentSubscriptionUpdateEventData.initialize(this, data_type, plan_id, subscription_id, merchant_id, merchant_address, user_address, token_id, start_time, expiration_time, charges_made, period_type, periods, interval, status, created_timestamp, updated_timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data_type, plan_id, subscription_id, merchant_id, merchant_address, user_address, token_id, start_time, expiration_time, charges_made, period_type, periods, interval, status, created_timestamp, updated_timestamp) { 
        obj['data_type'] = data_type;
        obj['plan_id'] = plan_id;
        obj['subscription_id'] = subscription_id;
        obj['merchant_id'] = merchant_id;
        obj['merchant_address'] = merchant_address;
        obj['user_address'] = user_address;
        obj['token_id'] = token_id;
        obj['start_time'] = start_time;
        obj['expiration_time'] = expiration_time;
        obj['charges_made'] = charges_made;
        obj['period_type'] = period_type;
        obj['periods'] = periods;
        obj['interval'] = interval;
        obj['status'] = status;
        obj['created_timestamp'] = created_timestamp;
        obj['updated_timestamp'] = updated_timestamp;
    }

    /**
     * Constructs a <code>PaymentSubscriptionUpdateEventData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentSubscriptionUpdateEventData} obj Optional instance to populate.
     * @return {module:model/PaymentSubscriptionUpdateEventData} The populated <code>PaymentSubscriptionUpdateEventData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentSubscriptionUpdateEventData();
            WebhookEventDataType.constructFromObject(data, obj);
            PaymentSubscription.constructFromObject(data, obj);

            if (data.hasOwnProperty('data_type')) {
                obj['data_type'] = ApiClient.convertToType(data['data_type'], 'String');
            }
            if (data.hasOwnProperty('plan_id')) {
                obj['plan_id'] = ApiClient.convertToType(data['plan_id'], 'String');
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
            if (data.hasOwnProperty('merchant_id')) {
                obj['merchant_id'] = ApiClient.convertToType(data['merchant_id'], 'String');
            }
            if (data.hasOwnProperty('merchant_address')) {
                obj['merchant_address'] = ApiClient.convertToType(data['merchant_address'], 'String');
            }
            if (data.hasOwnProperty('user_address')) {
                obj['user_address'] = ApiClient.convertToType(data['user_address'], 'String');
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('charge_amount')) {
                obj['charge_amount'] = ApiClient.convertToType(data['charge_amount'], 'String');
            }
            if (data.hasOwnProperty('start_time')) {
                obj['start_time'] = ApiClient.convertToType(data['start_time'], 'Number');
            }
            if (data.hasOwnProperty('expiration_time')) {
                obj['expiration_time'] = ApiClient.convertToType(data['expiration_time'], 'Number');
            }
            if (data.hasOwnProperty('charges_made')) {
                obj['charges_made'] = ApiClient.convertToType(data['charges_made'], 'Number');
            }
            if (data.hasOwnProperty('period_type')) {
                obj['period_type'] = PaymentSubscriptionPeriodType.constructFromObject(data['period_type']);
            }
            if (data.hasOwnProperty('periods')) {
                obj['periods'] = ApiClient.convertToType(data['periods'], 'Number');
            }
            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = PaymentSubscriptionStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('created_timestamp')) {
                obj['created_timestamp'] = ApiClient.convertToType(data['created_timestamp'], 'Number');
            }
            if (data.hasOwnProperty('updated_timestamp')) {
                obj['updated_timestamp'] = ApiClient.convertToType(data['updated_timestamp'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentSubscriptionUpdateEventData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentSubscriptionUpdateEventData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentSubscriptionUpdateEventData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['data_type'] && !(typeof data['data_type'] === 'string' || data['data_type'] instanceof String)) {
            throw new Error("Expected the field `data_type` to be a primitive type in the JSON string but got " + data['data_type']);
        }
        // ensure the json data is a string
        if (data['plan_id'] && !(typeof data['plan_id'] === 'string' || data['plan_id'] instanceof String)) {
            throw new Error("Expected the field `plan_id` to be a primitive type in the JSON string but got " + data['plan_id']);
        }
        // ensure the json data is a string
        if (data['subscription_id'] && !(typeof data['subscription_id'] === 'string' || data['subscription_id'] instanceof String)) {
            throw new Error("Expected the field `subscription_id` to be a primitive type in the JSON string but got " + data['subscription_id']);
        }
        // ensure the json data is a string
        if (data['merchant_id'] && !(typeof data['merchant_id'] === 'string' || data['merchant_id'] instanceof String)) {
            throw new Error("Expected the field `merchant_id` to be a primitive type in the JSON string but got " + data['merchant_id']);
        }
        // ensure the json data is a string
        if (data['merchant_address'] && !(typeof data['merchant_address'] === 'string' || data['merchant_address'] instanceof String)) {
            throw new Error("Expected the field `merchant_address` to be a primitive type in the JSON string but got " + data['merchant_address']);
        }
        // ensure the json data is a string
        if (data['user_address'] && !(typeof data['user_address'] === 'string' || data['user_address'] instanceof String)) {
            throw new Error("Expected the field `user_address` to be a primitive type in the JSON string but got " + data['user_address']);
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }
        // ensure the json data is a string
        if (data['charge_amount'] && !(typeof data['charge_amount'] === 'string' || data['charge_amount'] instanceof String)) {
            throw new Error("Expected the field `charge_amount` to be a primitive type in the JSON string but got " + data['charge_amount']);
        }

        return true;
    }


}

PaymentSubscriptionUpdateEventData.RequiredProperties = ["data_type", "plan_id", "subscription_id", "merchant_id", "merchant_address", "user_address", "token_id", "start_time", "expiration_time", "charges_made", "period_type", "periods", "interval", "status", "created_timestamp", "updated_timestamp"];

/**
 *  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The payment address update event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The suspended token event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data.
 * @member {module:model/PaymentSubscriptionUpdateEventData.DataTypeEnum} data_type
 */
PaymentSubscriptionUpdateEventData.prototype['data_type'] = undefined;

/**
 * The plan id in cobo.
 * @member {String} plan_id
 */
PaymentSubscriptionUpdateEventData.prototype['plan_id'] = undefined;

/**
 * The subscription id in cobo.
 * @member {String} subscription_id
 */
PaymentSubscriptionUpdateEventData.prototype['subscription_id'] = undefined;

/**
 * The merchant id in cobo.
 * @member {String} merchant_id
 */
PaymentSubscriptionUpdateEventData.prototype['merchant_id'] = undefined;

/**
 * The merchant address in cobo.
 * @member {String} merchant_address
 */
PaymentSubscriptionUpdateEventData.prototype['merchant_address'] = undefined;

/**
 * The user address in subscription.
 * @member {String} user_address
 */
PaymentSubscriptionUpdateEventData.prototype['user_address'] = undefined;

/**
 * The token_id in subscription.
 * @member {String} token_id
 */
PaymentSubscriptionUpdateEventData.prototype['token_id'] = undefined;

/**
 * The charge amount in subscription.
 * @member {String} charge_amount
 */
PaymentSubscriptionUpdateEventData.prototype['charge_amount'] = undefined;

/**
 * The subscription start timestamp.
 * @member {Number} start_time
 */
PaymentSubscriptionUpdateEventData.prototype['start_time'] = undefined;

/**
 * The subscription expired timestamp.
 * @member {Number} expiration_time
 */
PaymentSubscriptionUpdateEventData.prototype['expiration_time'] = undefined;

/**
 * The subscription charge times.
 * @member {Number} charges_made
 */
PaymentSubscriptionUpdateEventData.prototype['charges_made'] = undefined;

/**
 * @member {module:model/PaymentSubscriptionPeriodType} period_type
 */
PaymentSubscriptionUpdateEventData.prototype['period_type'] = undefined;

/**
 * @member {Number} periods
 */
PaymentSubscriptionUpdateEventData.prototype['periods'] = undefined;

/**
 * The subscription charge interval.
 * @member {Number} interval
 */
PaymentSubscriptionUpdateEventData.prototype['interval'] = undefined;

/**
 * @member {module:model/PaymentSubscriptionStatus} status
 */
PaymentSubscriptionUpdateEventData.prototype['status'] = undefined;

/**
 * The created time of the subscription, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentSubscriptionUpdateEventData.prototype['created_timestamp'] = undefined;

/**
 * The updated time of the subscription, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentSubscriptionUpdateEventData.prototype['updated_timestamp'] = undefined;


// Implement WebhookEventDataType interface:
/**
 *  The data type of the event. - `Transaction`: The transaction event data. - `TSSRequest`: The TSS request event data. - `Addresses`: The addresses event data. - `WalletInfo`: The wallet information event data. - `MPCVault`: The MPC vault event data. - `Chains`: The enabled chain event data. - `Tokens`: The enabled token event data. - `TokenListing`: The token listing event data.        - `PaymentOrder`: The payment order event data. - `PaymentRefund`: The payment refund event data. - `PaymentSettlement`: The payment settlement event data. - `PaymentTransaction`: The payment transaction event data. - `PaymentAddressUpdate`: The payment address update event data. - `BalanceUpdateInfo`: The balance update event data. - `SuspendedToken`: The suspended token event data. - `ComplianceDisposition`: The compliance disposition event data. - `ComplianceKytScreenings`: The compliance KYT screenings event data.
 * @member {module:model/WebhookEventDataType.DataTypeEnum} data_type
 */
WebhookEventDataType.prototype['data_type'] = undefined;
// Implement PaymentSubscription interface:
/**
 * The plan id in cobo.
 * @member {String} plan_id
 */
PaymentSubscription.prototype['plan_id'] = undefined;
/**
 * The subscription id in cobo.
 * @member {String} subscription_id
 */
PaymentSubscription.prototype['subscription_id'] = undefined;
/**
 * The merchant id in cobo.
 * @member {String} merchant_id
 */
PaymentSubscription.prototype['merchant_id'] = undefined;
/**
 * The merchant address in cobo.
 * @member {String} merchant_address
 */
PaymentSubscription.prototype['merchant_address'] = undefined;
/**
 * The user address in subscription.
 * @member {String} user_address
 */
PaymentSubscription.prototype['user_address'] = undefined;
/**
 * The token_id in subscription.
 * @member {String} token_id
 */
PaymentSubscription.prototype['token_id'] = undefined;
/**
 * The charge amount in subscription.
 * @member {String} charge_amount
 */
PaymentSubscription.prototype['charge_amount'] = undefined;
/**
 * The subscription start timestamp.
 * @member {Number} start_time
 */
PaymentSubscription.prototype['start_time'] = undefined;
/**
 * The subscription expired timestamp.
 * @member {Number} expiration_time
 */
PaymentSubscription.prototype['expiration_time'] = undefined;
/**
 * The subscription charge times.
 * @member {Number} charges_made
 */
PaymentSubscription.prototype['charges_made'] = undefined;
/**
 * @member {module:model/PaymentSubscriptionPeriodType} period_type
 */
PaymentSubscription.prototype['period_type'] = undefined;
/**
 * @member {Number} periods
 */
PaymentSubscription.prototype['periods'] = undefined;
/**
 * The subscription charge interval.
 * @member {Number} interval
 */
PaymentSubscription.prototype['interval'] = undefined;
/**
 * @member {module:model/PaymentSubscriptionStatus} status
 */
PaymentSubscription.prototype['status'] = undefined;
/**
 * The created time of the subscription, represented as a UNIX timestamp in seconds.
 * @member {Number} created_timestamp
 */
PaymentSubscription.prototype['created_timestamp'] = undefined;
/**
 * The updated time of the subscription, represented as a UNIX timestamp in seconds.
 * @member {Number} updated_timestamp
 */
PaymentSubscription.prototype['updated_timestamp'] = undefined;



/**
 * Allowed values for the <code>data_type</code> property.
 * @enum {String}
 * @readonly
 */
PaymentSubscriptionUpdateEventData['DataTypeEnum'] = {

    /**
     * value: "Transaction"
     * @const
     */
    "Transaction": "Transaction",

    /**
     * value: "TSSRequest"
     * @const
     */
    "TSSRequest": "TSSRequest",

    /**
     * value: "Addresses"
     * @const
     */
    "Addresses": "Addresses",

    /**
     * value: "WalletInfo"
     * @const
     */
    "WalletInfo": "WalletInfo",

    /**
     * value: "MPCVault"
     * @const
     */
    "MPCVault": "MPCVault",

    /**
     * value: "Chains"
     * @const
     */
    "Chains": "Chains",

    /**
     * value: "Tokens"
     * @const
     */
    "Tokens": "Tokens",

    /**
     * value: "TokenListing"
     * @const
     */
    "TokenListing": "TokenListing",

    /**
     * value: "PaymentOrder"
     * @const
     */
    "PaymentOrder": "PaymentOrder",

    /**
     * value: "PaymentRefund"
     * @const
     */
    "PaymentRefund": "PaymentRefund",

    /**
     * value: "PaymentSettlement"
     * @const
     */
    "PaymentSettlement": "PaymentSettlement",

    /**
     * value: "PaymentTransaction"
     * @const
     */
    "PaymentTransaction": "PaymentTransaction",

    /**
     * value: "PaymentAddressUpdate"
     * @const
     */
    "PaymentAddressUpdate": "PaymentAddressUpdate",

    /**
     * value: "PaymentSubscriptionUpdate"
     * @const
     */
    "PaymentSubscriptionUpdate": "PaymentSubscriptionUpdate",

    /**
     * value: "PaymentChargeUpdate"
     * @const
     */
    "PaymentChargeUpdate": "PaymentChargeUpdate",

    /**
     * value: "BalanceUpdateInfo"
     * @const
     */
    "BalanceUpdateInfo": "BalanceUpdateInfo",

    /**
     * value: "SuspendedToken"
     * @const
     */
    "SuspendedToken": "SuspendedToken",

    /**
     * value: "ComplianceDisposition"
     * @const
     */
    "ComplianceDisposition": "ComplianceDisposition",

    /**
     * value: "ComplianceKytScreenings"
     * @const
     */
    "ComplianceKytScreenings": "ComplianceKytScreenings",

    /**
     * value: "unknown_default_open_api"
     * @const
     */
    "unknown_default_open_api": "unknown_default_open_api"
};



export default PaymentSubscriptionUpdateEventData;

