/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PaymentSubscriptionActionType from './PaymentSubscriptionActionType';

/**
 * The PaymentApproveSubscriptionActionData model module.
 * @module model/PaymentApproveSubscriptionActionData
 */
class PaymentApproveSubscriptionActionData {
    /**
     * Constructs a new <code>PaymentApproveSubscriptionActionData</code>.
     * @alias module:model/PaymentApproveSubscriptionActionData
     * @param action_type {module:model/PaymentSubscriptionActionType} 
     * @param subscription_id {String} The subscription id in cobo.
     */
    constructor(action_type, subscription_id) { 
        
        PaymentApproveSubscriptionActionData.initialize(this, action_type, subscription_id);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, action_type, subscription_id) { 
        obj['action_type'] = action_type;
        obj['subscription_id'] = subscription_id;
    }

    /**
     * Constructs a <code>PaymentApproveSubscriptionActionData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PaymentApproveSubscriptionActionData} obj Optional instance to populate.
     * @return {module:model/PaymentApproveSubscriptionActionData} The populated <code>PaymentApproveSubscriptionActionData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PaymentApproveSubscriptionActionData();

            if (data.hasOwnProperty('action_type')) {
                obj['action_type'] = PaymentSubscriptionActionType.constructFromObject(data['action_type']);
            }
            if (data.hasOwnProperty('subscription_id')) {
                obj['subscription_id'] = ApiClient.convertToType(data['subscription_id'], 'String');
            }
            if (data.hasOwnProperty('permit_data')) {
                obj['permit_data'] = ApiClient.convertToType(data['permit_data'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PaymentApproveSubscriptionActionData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PaymentApproveSubscriptionActionData</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PaymentApproveSubscriptionActionData.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['subscription_id'] && !(typeof data['subscription_id'] === 'string' || data['subscription_id'] instanceof String)) {
            throw new Error("Expected the field `subscription_id` to be a primitive type in the JSON string but got " + data['subscription_id']);
        }
        // ensure the json data is a string
        if (data['permit_data'] && !(typeof data['permit_data'] === 'string' || data['permit_data'] instanceof String)) {
            throw new Error("Expected the field `permit_data` to be a primitive type in the JSON string but got " + data['permit_data']);
        }

        return true;
    }


}

PaymentApproveSubscriptionActionData.RequiredProperties = ["action_type", "subscription_id"];

/**
 * @member {module:model/PaymentSubscriptionActionType} action_type
 */
PaymentApproveSubscriptionActionData.prototype['action_type'] = undefined;

/**
 * The subscription id in cobo.
 * @member {String} subscription_id
 */
PaymentApproveSubscriptionActionData.prototype['subscription_id'] = undefined;

/**
 * The signature of permit.
 * @member {String} permit_data
 */
PaymentApproveSubscriptionActionData.prototype['permit_data'] = undefined;






export default PaymentApproveSubscriptionActionData;

