/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class PayoutStatus.
* @enum {}
* @readonly
*/
export default class PayoutStatus {
    
        /**
         * value: "None"
         * @const
         */
        "None" = "None";

    
        /**
         * value: "Initialized"
         * @const
         */
        "Initialized" = "Initialized";

    
        /**
         * value: "Pending"
         * @const
         */
        "Pending" = "Pending";

    
        /**
         * value: "PartiallyCompleted"
         * @const
         */
        "PartiallyCompleted" = "PartiallyCompleted";

    
        /**
         * value: "Failed"
         * @const
         */
        "Failed" = "Failed";

    
        /**
         * value: "Completed"
         * @const
         */
        "Completed" = "Completed";

    
        /**
         * value: "PendingApproval"
         * @const
         */
        "PendingApproval" = "PendingApproval";

    
        /**
         * value: "ApprovalFailed"
         * @const
         */
        "ApprovalFailed" = "ApprovalFailed";

    
        /**
         * value: "ApprovalRevoked"
         * @const
         */
        "ApprovalRevoked" = "ApprovalRevoked";

    
        /**
         * value: "ApprovalRevoking"
         * @const
         */
        "ApprovalRevoking" = "ApprovalRevoking";

    
        /**
         * value: "PendingRecipientConfirmation"
         * @const
         */
        "PendingRecipientConfirmation" = "PendingRecipientConfirmation";

    
        /**
         * value: "PartiallyCompletedFinal"
         * @const
         */
        "PartiallyCompletedFinal" = "PartiallyCompletedFinal";

    
        /**
         * value: "PendingTokenApproval"
         * @const
         */
        "PendingTokenApproval" = "PendingTokenApproval";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>PayoutStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/PayoutStatus} The enum <code>PayoutStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

