/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SkipCheckType from './SkipCheckType';

/**
 * The PreCheck model module.
 * @module model/PreCheck
 */
class PreCheck {
    /**
     * Constructs a new <code>PreCheck</code>.
     * Some validation settings for creating a transaction.
     * @alias module:model/PreCheck
     */
    constructor() { 
        
        PreCheck.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PreCheck</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PreCheck} obj Optional instance to populate.
     * @return {module:model/PreCheck} The populated <code>PreCheck</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PreCheck();

            if (data.hasOwnProperty('skip_checks')) {
                obj['skip_checks'] = ApiClient.convertToType(data['skip_checks'], [SkipCheckType]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PreCheck</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PreCheck</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['skip_checks'])) {
            throw new Error("Expected the field `skip_checks` to be an array in the JSON data but got " + data['skip_checks']);
        }

        return true;
    }


}



/**
 * Selection to skip verification.
 * @member {Array.<module:model/SkipCheckType>} skip_checks
 */
PreCheck.prototype['skip_checks'] = undefined;






export default PreCheck;

