/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReceivedAmountPerAddress model module.
 * @module model/ReceivedAmountPerAddress
 */
class ReceivedAmountPerAddress {
    /**
     * Constructs a new <code>ReceivedAmountPerAddress</code>.
     * Total amount of a specific token received at a given address.
     * @alias module:model/ReceivedAmountPerAddress
     * @param address {String} Receiving address.
     * @param total_received_amount {String} Total tokens received at this address, as a decimal string.
     */
    constructor(address, total_received_amount) { 
        
        ReceivedAmountPerAddress.initialize(this, address, total_received_amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, total_received_amount) { 
        obj['address'] = address;
        obj['total_received_amount'] = total_received_amount;
    }

    /**
     * Constructs a <code>ReceivedAmountPerAddress</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReceivedAmountPerAddress} obj Optional instance to populate.
     * @return {module:model/ReceivedAmountPerAddress} The populated <code>ReceivedAmountPerAddress</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReceivedAmountPerAddress();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('total_received_amount')) {
                obj['total_received_amount'] = ApiClient.convertToType(data['total_received_amount'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReceivedAmountPerAddress</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReceivedAmountPerAddress</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReceivedAmountPerAddress.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['total_received_amount'] && !(typeof data['total_received_amount'] === 'string' || data['total_received_amount'] instanceof String)) {
            throw new Error("Expected the field `total_received_amount` to be a primitive type in the JSON string but got " + data['total_received_amount']);
        }

        return true;
    }


}

ReceivedAmountPerAddress.RequiredProperties = ["address", "total_received_amount"];

/**
 * Receiving address.
 * @member {String} address
 */
ReceivedAmountPerAddress.prototype['address'] = undefined;

/**
 * Total tokens received at this address, as a decimal string.
 * @member {String} total_received_amount
 */
ReceivedAmountPerAddress.prototype['total_received_amount'] = undefined;






export default ReceivedAmountPerAddress;

