/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StellarContractCallContractType from './StellarContractCallContractType';
import StellarContractCallTrustLineOperationType from './StellarContractCallTrustLineOperationType';

/**
 * The StellarContractCallTrustLineParam model module.
 * @module model/StellarContractCallTrustLineParam
 */
class StellarContractCallTrustLineParam {
    /**
     * Constructs a new <code>StellarContractCallTrustLineParam</code>.
     * Parameters related to Stellar trustline operations.
     * @alias module:model/StellarContractCallTrustLineParam
     * @param contract_type {module:model/StellarContractCallContractType} 
     * @param token_id {String} The token ID, which is the unique identifier of a token.
     * @param operation_type {module:model/StellarContractCallTrustLineOperationType} 
     */
    constructor(contract_type, token_id, operation_type) { 
        
        StellarContractCallTrustLineParam.initialize(this, contract_type, token_id, operation_type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contract_type, token_id, operation_type) { 
        obj['contract_type'] = contract_type;
        obj['token_id'] = token_id;
        obj['operation_type'] = operation_type;
    }

    /**
     * Constructs a <code>StellarContractCallTrustLineParam</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StellarContractCallTrustLineParam} obj Optional instance to populate.
     * @return {module:model/StellarContractCallTrustLineParam} The populated <code>StellarContractCallTrustLineParam</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StellarContractCallTrustLineParam();

            if (data.hasOwnProperty('contract_type')) {
                obj['contract_type'] = StellarContractCallContractType.constructFromObject(data['contract_type']);
            }
            if (data.hasOwnProperty('token_id')) {
                obj['token_id'] = ApiClient.convertToType(data['token_id'], 'String');
            }
            if (data.hasOwnProperty('operation_type')) {
                obj['operation_type'] = StellarContractCallTrustLineOperationType.constructFromObject(data['operation_type']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StellarContractCallTrustLineParam</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StellarContractCallTrustLineParam</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StellarContractCallTrustLineParam.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['token_id'] && !(typeof data['token_id'] === 'string' || data['token_id'] instanceof String)) {
            throw new Error("Expected the field `token_id` to be a primitive type in the JSON string but got " + data['token_id']);
        }

        return true;
    }


}

StellarContractCallTrustLineParam.RequiredProperties = ["contract_type", "token_id", "operation_type"];

/**
 * @member {module:model/StellarContractCallContractType} contract_type
 */
StellarContractCallTrustLineParam.prototype['contract_type'] = undefined;

/**
 * The token ID, which is the unique identifier of a token.
 * @member {String} token_id
 */
StellarContractCallTrustLineParam.prototype['token_id'] = undefined;

/**
 * @member {module:model/StellarContractCallTrustLineOperationType} operation_type
 */
StellarContractCallTrustLineParam.prototype['operation_type'] = undefined;






export default StellarContractCallTrustLineParam;

