/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubmitKytResponse model module.
 * @module model/SubmitKytResponse
 */
class SubmitKytResponse {
    /**
     * Constructs a new <code>SubmitKytResponse</code>.
     * The response for a KYT (Know Your Transaction) submission request.
     * @alias module:model/SubmitKytResponse
     * @param transaction_id {String} The UUID of the transaction being processed for screened.
     * @param submitted {Boolean} Indicates whether the KYT submission was successfully submitted.
     */
    constructor(transaction_id, submitted) { 
        
        SubmitKytResponse.initialize(this, transaction_id, submitted);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transaction_id, submitted) { 
        obj['transaction_id'] = transaction_id;
        obj['submitted'] = submitted;
    }

    /**
     * Constructs a <code>SubmitKytResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmitKytResponse} obj Optional instance to populate.
     * @return {module:model/SubmitKytResponse} The populated <code>SubmitKytResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitKytResponse();

            if (data.hasOwnProperty('transaction_id')) {
                obj['transaction_id'] = ApiClient.convertToType(data['transaction_id'], 'String');
            }
            if (data.hasOwnProperty('submitted')) {
                obj['submitted'] = ApiClient.convertToType(data['submitted'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubmitKytResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubmitKytResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubmitKytResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['transaction_id'] && !(typeof data['transaction_id'] === 'string' || data['transaction_id'] instanceof String)) {
            throw new Error("Expected the field `transaction_id` to be a primitive type in the JSON string but got " + data['transaction_id']);
        }

        return true;
    }


}

SubmitKytResponse.RequiredProperties = ["transaction_id", "submitted"];

/**
 * The UUID of the transaction being processed for screened.
 * @member {String} transaction_id
 */
SubmitKytResponse.prototype['transaction_id'] = undefined;

/**
 * Indicates whether the KYT submission was successfully submitted.
 * @member {Boolean} submitted
 */
SubmitKytResponse.prototype['submitted'] = undefined;






export default SubmitKytResponse;

