/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class TokenizationPermissionAction.
* @enum {}
* @readonly
*/
export default class TokenizationPermissionAction {
    
        /**
         * value: "add"
         * @const
         */
        "add" = "add";

    
        /**
         * value: "remove"
         * @const
         */
        "remove" = "remove";

    
        /**
         * value: "set"
         * @const
         */
        "set" = "set";

    
        /**
         * value: "unknown_default_open_api"
         * @const
         */
        "unknown_default_open_api" = "unknown_default_open_api";

    

    /**
    * Returns a <code>TokenizationPermissionAction</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/TokenizationPermissionAction} The enum <code>TokenizationPermissionAction</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

