/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenizationAppInitiator from './TokenizationAppInitiator';

/**
 * The TokenizationArchiveTokenRequest model module.
 * @module model/TokenizationArchiveTokenRequest
 */
class TokenizationArchiveTokenRequest {
    /**
     * Constructs a new <code>TokenizationArchiveTokenRequest</code>.
     * @alias module:model/TokenizationArchiveTokenRequest
     * @implements module:model/TokenizationAppInitiator
     */
    constructor() { 
        TokenizationAppInitiator.initialize(this);
        TokenizationArchiveTokenRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TokenizationArchiveTokenRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenizationArchiveTokenRequest} obj Optional instance to populate.
     * @return {module:model/TokenizationArchiveTokenRequest} The populated <code>TokenizationArchiveTokenRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenizationArchiveTokenRequest();
            TokenizationAppInitiator.constructFromObject(data, obj);

            if (data.hasOwnProperty('app_initiator')) {
                obj['app_initiator'] = ApiClient.convertToType(data['app_initiator'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenizationArchiveTokenRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenizationArchiveTokenRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['app_initiator'] && !(typeof data['app_initiator'] === 'string' || data['app_initiator'] instanceof String)) {
            throw new Error("Expected the field `app_initiator` to be a primitive type in the JSON string but got " + data['app_initiator']);
        }

        return true;
    }


}



/**
 * The initiator of the tokenization activity. If you do not specify this property, the WaaS service will automatically designate the API key as the initiator.
 * @member {String} app_initiator
 */
TokenizationArchiveTokenRequest.prototype['app_initiator'] = undefined;


// Implement TokenizationAppInitiator interface:
/**
 * The initiator of the tokenization activity. If you do not specify this property, the WaaS service will automatically designate the API key as the initiator.
 * @member {String} app_initiator
 */
TokenizationAppInitiator.prototype['app_initiator'] = undefined;




export default TokenizationArchiveTokenRequest;

