/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TokenizationERC20WrappedTokenPermissionParams from './TokenizationERC20WrappedTokenPermissionParams';
import TokenizationTokenStandard from './TokenizationTokenStandard';

/**
 * The TokenizationERC20WrappedTokenParams model module.
 * @module model/TokenizationERC20WrappedTokenParams
 */
class TokenizationERC20WrappedTokenParams {
    /**
     * Constructs a new <code>TokenizationERC20WrappedTokenParams</code>.
     * @alias module:model/TokenizationERC20WrappedTokenParams
     * @param standard {module:model/TokenizationTokenStandard} 
     * @param name {String} The name of the token.
     * @param symbol {String} The symbol of the token.
     * @param underlying_token {String} The address of the underlying token that this tokenized asset represents.
     */
    constructor(standard, name, symbol, underlying_token) { 
        
        TokenizationERC20WrappedTokenParams.initialize(this, standard, name, symbol, underlying_token);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, standard, name, symbol, underlying_token) { 
        obj['standard'] = standard;
        obj['name'] = name;
        obj['symbol'] = symbol;
        obj['underlying_token'] = underlying_token;
    }

    /**
     * Constructs a <code>TokenizationERC20WrappedTokenParams</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TokenizationERC20WrappedTokenParams} obj Optional instance to populate.
     * @return {module:model/TokenizationERC20WrappedTokenParams} The populated <code>TokenizationERC20WrappedTokenParams</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TokenizationERC20WrappedTokenParams();

            if (data.hasOwnProperty('standard')) {
                obj['standard'] = TokenizationTokenStandard.constructFromObject(data['standard']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('symbol')) {
                obj['symbol'] = ApiClient.convertToType(data['symbol'], 'String');
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = TokenizationERC20WrappedTokenPermissionParams.constructFromObject(data['permissions']);
            }
            if (data.hasOwnProperty('token_access_activated')) {
                obj['token_access_activated'] = ApiClient.convertToType(data['token_access_activated'], 'Boolean');
            }
            if (data.hasOwnProperty('underlying_token')) {
                obj['underlying_token'] = ApiClient.convertToType(data['underlying_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TokenizationERC20WrappedTokenParams</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TokenizationERC20WrappedTokenParams</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TokenizationERC20WrappedTokenParams.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['symbol'] && !(typeof data['symbol'] === 'string' || data['symbol'] instanceof String)) {
            throw new Error("Expected the field `symbol` to be a primitive type in the JSON string but got " + data['symbol']);
        }
        // validate the optional field `permissions`
        if (data['permissions']) { // data not null
          if (!!TokenizationERC20WrappedTokenPermissionParams.validateJSON) {
            TokenizationERC20WrappedTokenPermissionParams.validateJSON(data['permissions']);
          }
        }
        // ensure the json data is a string
        if (data['underlying_token'] && !(typeof data['underlying_token'] === 'string' || data['underlying_token'] instanceof String)) {
            throw new Error("Expected the field `underlying_token` to be a primitive type in the JSON string but got " + data['underlying_token']);
        }

        return true;
    }


}

TokenizationERC20WrappedTokenParams.RequiredProperties = ["standard", "name", "symbol", "underlying_token"];

/**
 * @member {module:model/TokenizationTokenStandard} standard
 */
TokenizationERC20WrappedTokenParams.prototype['standard'] = undefined;

/**
 * The name of the token.
 * @member {String} name
 */
TokenizationERC20WrappedTokenParams.prototype['name'] = undefined;

/**
 * The symbol of the token.
 * @member {String} symbol
 */
TokenizationERC20WrappedTokenParams.prototype['symbol'] = undefined;

/**
 * @member {module:model/TokenizationERC20WrappedTokenPermissionParams} permissions
 */
TokenizationERC20WrappedTokenParams.prototype['permissions'] = undefined;

/**
 * Whether the allowlist feature is activated for the token. When activated, only addresses in the allowlist can perform token operations.
 * @member {Boolean} token_access_activated
 * @default false
 */
TokenizationERC20WrappedTokenParams.prototype['token_access_activated'] = false;

/**
 * The address of the underlying token that this tokenized asset represents.
 * @member {String} underlying_token
 */
TokenizationERC20WrappedTokenParams.prototype['underlying_token'] = undefined;






export default TokenizationERC20WrappedTokenParams;

