/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DestinationType from './DestinationType';

/**
 * The UpdateDestinationRequest model module.
 * @module model/UpdateDestinationRequest
 */
class UpdateDestinationRequest {
    /**
     * Constructs a new <code>UpdateDestinationRequest</code>.
     * @alias module:model/UpdateDestinationRequest
     * @param updated_destination_name {String} The updated destination name.
     * @param updated_destination_type {module:model/DestinationType} 
     */
    constructor(updated_destination_name, updated_destination_type) { 
        
        UpdateDestinationRequest.initialize(this, updated_destination_name, updated_destination_type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, updated_destination_name, updated_destination_type) { 
        obj['updated_destination_name'] = updated_destination_name;
        obj['updated_destination_type'] = updated_destination_type;
    }

    /**
     * Constructs a <code>UpdateDestinationRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDestinationRequest} obj Optional instance to populate.
     * @return {module:model/UpdateDestinationRequest} The populated <code>UpdateDestinationRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDestinationRequest();

            if (data.hasOwnProperty('updated_destination_name')) {
                obj['updated_destination_name'] = ApiClient.convertToType(data['updated_destination_name'], 'String');
            }
            if (data.hasOwnProperty('updated_destination_type')) {
                obj['updated_destination_type'] = DestinationType.constructFromObject(data['updated_destination_type']);
            }
            if (data.hasOwnProperty('updated_merchant_id')) {
                obj['updated_merchant_id'] = ApiClient.convertToType(data['updated_merchant_id'], 'String');
            }
            if (data.hasOwnProperty('updated_country')) {
                obj['updated_country'] = ApiClient.convertToType(data['updated_country'], 'String');
            }
            if (data.hasOwnProperty('updated_email')) {
                obj['updated_email'] = ApiClient.convertToType(data['updated_email'], 'String');
            }
            if (data.hasOwnProperty('updated_contact_address')) {
                obj['updated_contact_address'] = ApiClient.convertToType(data['updated_contact_address'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDestinationRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDestinationRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateDestinationRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['updated_destination_name'] && !(typeof data['updated_destination_name'] === 'string' || data['updated_destination_name'] instanceof String)) {
            throw new Error("Expected the field `updated_destination_name` to be a primitive type in the JSON string but got " + data['updated_destination_name']);
        }
        // ensure the json data is a string
        if (data['updated_merchant_id'] && !(typeof data['updated_merchant_id'] === 'string' || data['updated_merchant_id'] instanceof String)) {
            throw new Error("Expected the field `updated_merchant_id` to be a primitive type in the JSON string but got " + data['updated_merchant_id']);
        }
        // ensure the json data is a string
        if (data['updated_country'] && !(typeof data['updated_country'] === 'string' || data['updated_country'] instanceof String)) {
            throw new Error("Expected the field `updated_country` to be a primitive type in the JSON string but got " + data['updated_country']);
        }
        // ensure the json data is a string
        if (data['updated_email'] && !(typeof data['updated_email'] === 'string' || data['updated_email'] instanceof String)) {
            throw new Error("Expected the field `updated_email` to be a primitive type in the JSON string but got " + data['updated_email']);
        }
        // ensure the json data is a string
        if (data['updated_contact_address'] && !(typeof data['updated_contact_address'] === 'string' || data['updated_contact_address'] instanceof String)) {
            throw new Error("Expected the field `updated_contact_address` to be a primitive type in the JSON string but got " + data['updated_contact_address']);
        }

        return true;
    }


}

UpdateDestinationRequest.RequiredProperties = ["updated_destination_name", "updated_destination_type"];

/**
 * The updated destination name.
 * @member {String} updated_destination_name
 */
UpdateDestinationRequest.prototype['updated_destination_name'] = undefined;

/**
 * @member {module:model/DestinationType} updated_destination_type
 */
UpdateDestinationRequest.prototype['updated_destination_type'] = undefined;

/**
 * The updated ID of the merchant linked to the destination.
 * @member {String} updated_merchant_id
 */
UpdateDestinationRequest.prototype['updated_merchant_id'] = undefined;

/**
 * The updated country of the destination, in ISO 3166-1 alpha-3 format.
 * @member {String} updated_country
 */
UpdateDestinationRequest.prototype['updated_country'] = undefined;

/**
 * The updated email of the destination.
 * @member {String} updated_email
 */
UpdateDestinationRequest.prototype['updated_email'] = undefined;

/**
 * The updated contact address of the destination.
 * @member {String} updated_contact_address
 */
UpdateDestinationRequest.prototype['updated_contact_address'] = undefined;






export default UpdateDestinationRequest;

