/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import IntermediaryBankInfo from './IntermediaryBankInfo';

/**
 * The UpdateDestinationBankAccount model module.
 * @module model/UpdateDestinationBankAccount
 */
class UpdateDestinationBankAccount {
    /**
     * Constructs a new <code>UpdateDestinationBankAccount</code>.
     * @alias module:model/UpdateDestinationBankAccount
     * @param account_alias {String} The alias of the bank account.
     * @param account_number {String} The bank account number.
     * @param swift_code {String} The SWIFT or BIC code of the bank.
     * @param currency {String} The currency of the bank account.
     * @param beneficiary_name {String} The name of the account holder.
     * @param beneficiary_address {String} The address of the account holder.
     * @param bank_name {String} The name of the bank.
     * @param bank_address {String} The address of the bank.
     */
    constructor(account_alias, account_number, swift_code, currency, beneficiary_name, beneficiary_address, bank_name, bank_address) { 
        
        UpdateDestinationBankAccount.initialize(this, account_alias, account_number, swift_code, currency, beneficiary_name, beneficiary_address, bank_name, bank_address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, account_alias, account_number, swift_code, currency, beneficiary_name, beneficiary_address, bank_name, bank_address) { 
        obj['account_alias'] = account_alias;
        obj['account_number'] = account_number;
        obj['swift_code'] = swift_code;
        obj['currency'] = currency;
        obj['beneficiary_name'] = beneficiary_name;
        obj['beneficiary_address'] = beneficiary_address;
        obj['bank_name'] = bank_name;
        obj['bank_address'] = bank_address;
    }

    /**
     * Constructs a <code>UpdateDestinationBankAccount</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateDestinationBankAccount} obj Optional instance to populate.
     * @return {module:model/UpdateDestinationBankAccount} The populated <code>UpdateDestinationBankAccount</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateDestinationBankAccount();

            if (data.hasOwnProperty('account_alias')) {
                obj['account_alias'] = ApiClient.convertToType(data['account_alias'], 'String');
            }
            if (data.hasOwnProperty('account_number')) {
                obj['account_number'] = ApiClient.convertToType(data['account_number'], 'String');
            }
            if (data.hasOwnProperty('swift_code')) {
                obj['swift_code'] = ApiClient.convertToType(data['swift_code'], 'String');
            }
            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('beneficiary_name')) {
                obj['beneficiary_name'] = ApiClient.convertToType(data['beneficiary_name'], 'String');
            }
            if (data.hasOwnProperty('beneficiary_address')) {
                obj['beneficiary_address'] = ApiClient.convertToType(data['beneficiary_address'], 'String');
            }
            if (data.hasOwnProperty('bank_name')) {
                obj['bank_name'] = ApiClient.convertToType(data['bank_name'], 'String');
            }
            if (data.hasOwnProperty('bank_address')) {
                obj['bank_address'] = ApiClient.convertToType(data['bank_address'], 'String');
            }
            if (data.hasOwnProperty('iban_code')) {
                obj['iban_code'] = ApiClient.convertToType(data['iban_code'], 'String');
            }
            if (data.hasOwnProperty('further_credit')) {
                obj['further_credit'] = ApiClient.convertToType(data['further_credit'], 'String');
            }
            if (data.hasOwnProperty('intermediary_bank_info')) {
                obj['intermediary_bank_info'] = IntermediaryBankInfo.constructFromObject(data['intermediary_bank_info']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateDestinationBankAccount</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateDestinationBankAccount</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of UpdateDestinationBankAccount.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['account_alias'] && !(typeof data['account_alias'] === 'string' || data['account_alias'] instanceof String)) {
            throw new Error("Expected the field `account_alias` to be a primitive type in the JSON string but got " + data['account_alias']);
        }
        // ensure the json data is a string
        if (data['account_number'] && !(typeof data['account_number'] === 'string' || data['account_number'] instanceof String)) {
            throw new Error("Expected the field `account_number` to be a primitive type in the JSON string but got " + data['account_number']);
        }
        // ensure the json data is a string
        if (data['swift_code'] && !(typeof data['swift_code'] === 'string' || data['swift_code'] instanceof String)) {
            throw new Error("Expected the field `swift_code` to be a primitive type in the JSON string but got " + data['swift_code']);
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['beneficiary_name'] && !(typeof data['beneficiary_name'] === 'string' || data['beneficiary_name'] instanceof String)) {
            throw new Error("Expected the field `beneficiary_name` to be a primitive type in the JSON string but got " + data['beneficiary_name']);
        }
        // ensure the json data is a string
        if (data['beneficiary_address'] && !(typeof data['beneficiary_address'] === 'string' || data['beneficiary_address'] instanceof String)) {
            throw new Error("Expected the field `beneficiary_address` to be a primitive type in the JSON string but got " + data['beneficiary_address']);
        }
        // ensure the json data is a string
        if (data['bank_name'] && !(typeof data['bank_name'] === 'string' || data['bank_name'] instanceof String)) {
            throw new Error("Expected the field `bank_name` to be a primitive type in the JSON string but got " + data['bank_name']);
        }
        // ensure the json data is a string
        if (data['bank_address'] && !(typeof data['bank_address'] === 'string' || data['bank_address'] instanceof String)) {
            throw new Error("Expected the field `bank_address` to be a primitive type in the JSON string but got " + data['bank_address']);
        }
        // ensure the json data is a string
        if (data['iban_code'] && !(typeof data['iban_code'] === 'string' || data['iban_code'] instanceof String)) {
            throw new Error("Expected the field `iban_code` to be a primitive type in the JSON string but got " + data['iban_code']);
        }
        // ensure the json data is a string
        if (data['further_credit'] && !(typeof data['further_credit'] === 'string' || data['further_credit'] instanceof String)) {
            throw new Error("Expected the field `further_credit` to be a primitive type in the JSON string but got " + data['further_credit']);
        }
        // validate the optional field `intermediary_bank_info`
        if (data['intermediary_bank_info']) { // data not null
          if (!!IntermediaryBankInfo.validateJSON) {
            IntermediaryBankInfo.validateJSON(data['intermediary_bank_info']);
          }
        }

        return true;
    }


}

UpdateDestinationBankAccount.RequiredProperties = ["account_alias", "account_number", "swift_code", "currency", "beneficiary_name", "beneficiary_address", "bank_name", "bank_address"];

/**
 * The alias of the bank account.
 * @member {String} account_alias
 */
UpdateDestinationBankAccount.prototype['account_alias'] = undefined;

/**
 * The bank account number.
 * @member {String} account_number
 */
UpdateDestinationBankAccount.prototype['account_number'] = undefined;

/**
 * The SWIFT or BIC code of the bank.
 * @member {String} swift_code
 */
UpdateDestinationBankAccount.prototype['swift_code'] = undefined;

/**
 * The currency of the bank account.
 * @member {String} currency
 */
UpdateDestinationBankAccount.prototype['currency'] = undefined;

/**
 * The name of the account holder.
 * @member {String} beneficiary_name
 */
UpdateDestinationBankAccount.prototype['beneficiary_name'] = undefined;

/**
 * The address of the account holder.
 * @member {String} beneficiary_address
 */
UpdateDestinationBankAccount.prototype['beneficiary_address'] = undefined;

/**
 * The name of the bank.
 * @member {String} bank_name
 */
UpdateDestinationBankAccount.prototype['bank_name'] = undefined;

/**
 * The address of the bank.
 * @member {String} bank_address
 */
UpdateDestinationBankAccount.prototype['bank_address'] = undefined;

/**
 * The IBAN code of the bank account.
 * @member {String} iban_code
 */
UpdateDestinationBankAccount.prototype['iban_code'] = undefined;

/**
 * The further credit of the bank account.
 * @member {String} further_credit
 */
UpdateDestinationBankAccount.prototype['further_credit'] = undefined;

/**
 * @member {module:model/IntermediaryBankInfo} intermediary_bank_info
 */
UpdateDestinationBankAccount.prototype['intermediary_bank_info'] = undefined;






export default UpdateDestinationBankAccount;

