/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CommissionFeeDetail from '../model/CommissionFeeDetail';
import ErrorResponse from '../model/ErrorResponse';
import TransactionRequestTypeParams from '../model/TransactionRequestTypeParams';

/**
* InternalFeeEngine service.
* @module api/InternalFeeEngineApi
*/
export default class InternalFeeEngineApi {

    /**
    * Constructs a new InternalFeeEngineApi. 
    * @alias module:api/InternalFeeEngineApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get commission fee
     * This operation retrieves commission fee. 
     * @param {String} request_id Unique request identifier
     * @param {Object} opts Optional parameters
     * @param {Number} [business_type_id] 
     * @param {Number} [amount] Transaction amount in smallest unit
     * @param {String} [chain_id] Blockchain chain ID
     * @param {String} [token_id] Token ID
     * @param {String} [wallet_id] Wallet ID
     * @param {Number} [wallet_type] Wallet type
     * @param {module:model/TransactionRequestTypeParams} [request_type] 
     * @param {Object.<String, {String: Object}>} [strategy_context] Strategy context parameters. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/CommissionFeeDetail>} and HTTP response
     */
    getCommissionFeeWithHttpInfo(request_id, opts) {
      opts = opts || {};
      let postBody = null;
      if (postBody && postBody.toJSON) {
          postBody = postBody.toJSON()
      }
      // verify the required parameter 'request_id' is set
      if (request_id === undefined || request_id === null) {
        throw new Error("Missing the required parameter 'request_id' when calling getCommissionFee");
      }

      let pathParams = {
      };
      let queryParams = {
        'request_id': request_id,
        'business_type_id': opts['business_type_id'],
        'amount': opts['amount'],
        'chain_id': opts['chain_id'],
        'token_id': opts['token_id'],
        'wallet_id': opts['wallet_id'],
        'wallet_type': opts['wallet_type'],
        'request_type': opts['request_type'],
        'strategy_context': opts['strategy_context']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['CoboAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [CommissionFeeDetail];
      return this.apiClient.callApi(
        '/internal/commission_fee', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get commission fee
     * This operation retrieves commission fee. 
     * @param {String} request_id Unique request identifier
     * @param {Object} opts Optional parameters
     * @param {Number} opts.business_type_id 
     * @param {Number} opts.amount Transaction amount in smallest unit
     * @param {String} opts.chain_id Blockchain chain ID
     * @param {String} opts.token_id Token ID
     * @param {String} opts.wallet_id Wallet ID
     * @param {Number} opts.wallet_type Wallet type
     * @param {module:model/TransactionRequestTypeParams} opts.request_type 
     * @param {Object.<String, {String: Object}>} opts.strategy_context Strategy context parameters. 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/CommissionFeeDetail>}
     */
    getCommissionFee(request_id, opts) {
      return this.getCommissionFeeWithHttpInfo(request_id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
