/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.AutoSweepTask();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AutoSweepTask', function() {
    it('should create an instance of AutoSweepTask', function() {
      // uncomment below and update the code to test AutoSweepTask
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be.a(CoboWaas2.AutoSweepTask);
    });

    it('should have the property task_id (base name: "task_id")', function() {
      // uncomment below and update the code to test the property task_id
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property wallet_id (base name: "wallet_id")', function() {
      // uncomment below and update the code to test the property wallet_id
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property token_id (base name: "token_id")', function() {
      // uncomment below and update the code to test the property token_id
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property transaction_ids (base name: "transaction_ids")', function() {
      // uncomment below and update the code to test the property transaction_ids
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property failed_reasons (base name: "failed_reasons")', function() {
      // uncomment below and update the code to test the property failed_reasons
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property created_timestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property created_timestamp
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

    it('should have the property updated_timestamp (base name: "updated_timestamp")', function() {
      // uncomment below and update the code to test the property updated_timestamp
      //var instance = new CoboWaas2.AutoSweepTask();
      //expect(instance).to.be();
    });

  });

}));
