/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ComplianceKyaScreeningsUpdateEventData', function() {
    it('should create an instance of ComplianceKyaScreeningsUpdateEventData', function() {
      // uncomment below and update the code to test ComplianceKyaScreeningsUpdateEventData
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be.a(CoboWaas2.ComplianceKyaScreeningsUpdateEventData);
    });

    it('should have the property data_type (base name: "data_type")', function() {
      // uncomment below and update the code to test the property data_type
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

    it('should have the property screening_id (base name: "screening_id")', function() {
      // uncomment below and update the code to test the property screening_id
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

    it('should have the property chain_id (base name: "chain_id")', function() {
      // uncomment below and update the code to test the property chain_id
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

    it('should have the property created_timestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property created_timestamp
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

    it('should have the property updated_timestamp (base name: "updated_timestamp")', function() {
      // uncomment below and update the code to test the property updated_timestamp
      //var instance = new CoboWaas2.ComplianceKyaScreeningsUpdateEventData();
      //expect(instance).to.be();
    });

  });

}));
