/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.Counterparty();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Counterparty', function() {
    it('should create an instance of Counterparty', function() {
      // uncomment below and update the code to test Counterparty
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be.a(CoboWaas2.Counterparty);
    });

    it('should have the property counterparty_id (base name: "counterparty_id")', function() {
      // uncomment below and update the code to test the property counterparty_id
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property counterparty_type (base name: "counterparty_type")', function() {
      // uncomment below and update the code to test the property counterparty_type
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property counterparty_name (base name: "counterparty_name")', function() {
      // uncomment below and update the code to test the property counterparty_name
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property contact_address (base name: "contact_address")', function() {
      // uncomment below and update the code to test the property contact_address
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property created_timestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property created_timestamp
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

    it('should have the property updated_timestamp (base name: "updated_timestamp")', function() {
      // uncomment below and update the code to test the property updated_timestamp
      //var instance = new CoboWaas2.Counterparty();
      //expect(instance).to.be();
    });

  });

}));
