/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.PaymentSubscriptionActionData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentSubscriptionActionData', function() {
    it('should create an instance of PaymentSubscriptionActionData', function() {
      // uncomment below and update the code to test PaymentSubscriptionActionData
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be.a(CoboWaas2.PaymentSubscriptionActionData);
    });

    it('should have the property action_type (base name: "action_type")', function() {
      // uncomment below and update the code to test the property action_type
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property user_address (base name: "user_address")', function() {
      // uncomment below and update the code to test the property user_address
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property token_id (base name: "token_id")', function() {
      // uncomment below and update the code to test the property token_id
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property charge_amount (base name: "charge_amount")', function() {
      // uncomment below and update the code to test the property charge_amount
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property subscription_id (base name: "subscription_id")', function() {
      // uncomment below and update the code to test the property subscription_id
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property signature (base name: "signature")', function() {
      // uncomment below and update the code to test the property signature
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property deadline (base name: "deadline")', function() {
      // uncomment below and update the code to test the property deadline
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property periods (base name: "periods")', function() {
      // uncomment below and update the code to test the property periods
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

    it('should have the property new_plan_id (base name: "new_plan_id")', function() {
      // uncomment below and update the code to test the property new_plan_id
      //var instance = new CoboWaas2.PaymentSubscriptionActionData();
      //expect(instance).to.be();
    });

  });

}));
