/**
 * Cobo Wallet as a Service 2.0
 *
 * Contact: help@cobo.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.CoboWaas2);
  }
}(this, function(expect, CoboWaas2) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new CoboWaas2.PaymentPayout();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentPayout', function() {
    it('should create an instance of PaymentPayout', function() {
      // uncomment below and update the code to test PaymentPayout
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be.a(CoboWaas2.PaymentPayout);
    });

    it('should have the property payout_id (base name: "payout_id")', function() {
      // uncomment below and update the code to test the property payout_id
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property request_id (base name: "request_id")', function() {
      // uncomment below and update the code to test the property request_id
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property payout_channel (base name: "payout_channel")', function() {
      // uncomment below and update the code to test the property payout_channel
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property source_account (base name: "source_account")', function() {
      // uncomment below and update the code to test the property source_account
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property payout_items (base name: "payout_items")', function() {
      // uncomment below and update the code to test the property payout_items
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property recipient_info (base name: "recipient_info")', function() {
      // uncomment below and update the code to test the property recipient_info
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property initiator (base name: "initiator")', function() {
      // uncomment below and update the code to test the property initiator
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property actual_payout_amount (base name: "actual_payout_amount")', function() {
      // uncomment below and update the code to test the property actual_payout_amount
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property commission_fees (base name: "commission_fees")', function() {
      // uncomment below and update the code to test the property commission_fees
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property remark (base name: "remark")', function() {
      // uncomment below and update the code to test the property remark
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property created_timestamp (base name: "created_timestamp")', function() {
      // uncomment below and update the code to test the property created_timestamp
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

    it('should have the property updated_timestamp (base name: "updated_timestamp")', function() {
      // uncomment below and update the code to test the property updated_timestamp
      //var instance = new CoboWaas2.PaymentPayout();
      //expect(instance).to.be();
    });

  });

}));
